// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package com.digitalasset.canton.ledger.api.messages.update

import cats.implicits.toTraverseOps
import com.daml.ledger.api.v2.update_service
import com.daml.platform.v1.page_tokens
import com.digitalasset.canton.crypto.{Hash, HashAlgorithm, HashPurpose}
import com.digitalasset.canton.data.Offset
import com.digitalasset.canton.ledger.api.util.UpdateFormatHashUtils
import com.digitalasset.canton.ledger.api.validation.UpdateServiceRequestValidator.Result
import com.digitalasset.canton.ledger.api.validation.{ParticipantOffsetValidator, ValidationErrors}
import com.digitalasset.canton.ledger.error.groups.RequestValidationErrors
import com.digitalasset.canton.logging.ErrorLoggingContext
import com.digitalasset.daml.lf.data.Ref
import com.google.protobuf.ByteString

import scala.util.Try

final case class UpdatesPageToken(
    lowestPageOffsetExclusive: Option[Offset],
    highestPageOffsetInclusive: Option[Offset],
    participantIdChecksum: ByteString,
    requestChecksum: ByteString,
) {
  def toProto: page_tokens.UpdatesPageToken =
    page_tokens.UpdatesPageToken(
      lowestPageOffsetExclusive = lowestPageOffsetExclusive.fold(0L)(_.unwrap),
      highestPageOffsetInclusive = highestPageOffsetInclusive.fold(0L)(_.unwrap),
      version = UpdatesPageToken.Version,
      participantIdChecksum = participantIdChecksum,
      requestChecksum = requestChecksum,
    )

  @SuppressWarnings(Array("com.digitalasset.canton.ProtobufToByteString"))
  def toOpaqueByteString: ByteString =
    toProto.toByteString
}

object UpdatesPageToken {

  /** Token version used to detect format mismatch. Must be bumped every time protobuf token
    * structure is changed.
    */
  val Version: Int = 1

  def requestChecksum(request: update_service.GetUpdatesPageRequest): ByteString =
    Hash
      .build(HashPurpose.UpdatesPageToken, HashAlgorithm.Sha256)
      .addOptional(request.beginOffsetExclusive, _.addLong)
      .addOptional(request.endOffsetInclusive, _.addLong)
      .addOptional(request.maxPageSize, _.addInt)
      .addOptional(request.updateFormat, UpdateFormatHashUtils.hashUpdateFormat)
      .addBool(request.descendingOrder)
      .finish()
      .unwrap
      .substring(0, 4)

  def participantChecksum(participantId: Ref.ParticipantId): ByteString = Hash
    .build(HashPurpose.UpdatesPageToken, HashAlgorithm.Sha256)
    .addString(participantId)
    .finish()
    .unwrap
    .substring(0, 4)

  def validateToken(
      updatesPageToken: com.daml.platform.v1.page_tokens.UpdatesPageToken,
      request: update_service.GetUpdatesPageRequest,
      participantId: Ref.ParticipantId,
  )(implicit errorLoggingContext: ErrorLoggingContext): Result[UpdatesPageToken] =
    for {
      _ <- Either.cond(
        updatesPageToken.version == Version,
        (),
        RequestValidationErrors.InvalidUpdatesPageToken
          .Reject("Page continuation token was generated by a different Canton version")
          .asGrpcError,
      )
      _ <- Either.cond(
        updatesPageToken.requestChecksum == requestChecksum(request),
        (),
        RequestValidationErrors.InvalidUpdatesPageToken
          .Reject("Page token was obtained with different request parameters")
          .asGrpcError,
      )
      _ <- Either.cond(
        updatesPageToken.participantIdChecksum == participantChecksum(participantId),
        (),
        RequestValidationErrors.InvalidUpdatesPageToken
          .Reject("Page token was obtained from an other participant node")
          .asGrpcError,
      )
      lowestOffsetExcl <- ParticipantOffsetValidator
        .validateNonNegative(
          updatesPageToken.lowestPageOffsetExclusive,
          "lowestPageOffsetExclusive",
        )
        .left
        .map(_ =>
          RequestValidationErrors.InvalidUpdatesPageToken
            .Reject("lowestPageOffsetExclusive bound is negative")
            .asGrpcError
        )
      highestOffsetIncl <- ParticipantOffsetValidator
        .validateNonNegative(
          updatesPageToken.highestPageOffsetInclusive,
          "highestPageOffsetInclusive",
        )
        .left
        .map(_ =>
          RequestValidationErrors.InvalidUpdatesPageToken
            .Reject("highestPageOffsetInclusive bound is negative")
            .asGrpcError
        )
    } yield UpdatesPageToken(
      lowestOffsetExcl,
      highestOffsetIncl,
      updatesPageToken.participantIdChecksum,
      updatesPageToken.requestChecksum,
    )

  private def deserializePB(byteString: ByteString)(implicit
      errorLoggingContext: ErrorLoggingContext
  ): Result[page_tokens.UpdatesPageToken] =
    Try(page_tokens.UpdatesPageToken.parseFrom(byteString.toByteArray)).toEither.left.map(_ =>
      ValidationErrors.invalidField(
        fieldName = "stream_continuation_token",
        message = "Invalid continuation token for GetActiveContractsRequest",
      )
    )

  def validateToken(
      request: update_service.GetUpdatesPageRequest,
      participantId: Ref.ParticipantId,
  )(implicit errorLoggingContext: ErrorLoggingContext): Result[Option[UpdatesPageToken]] =
    request.pageToken.traverse { token =>
      for {
        parsedToken <- deserializePB(token)
        validated <- validateToken(parsedToken, request, participantId)
      } yield validated
    }
}
