canton {
  features {
    # required for key export
    enable-preview-commands = yes
  }
  parameters {
    manual-start = no
    timeouts.processing.slow-future-warn = 20.seconds
    # Set to 10x confirmation timeout as suggested by Canton.
    timeouts.processing.sequenced-event-processing-bound = 10m
  }
}
