_baseparticipant {
  parameters {
    alpha-version-support = yes
    beta-version-support = yes
  }
  ledger-api {
    command-service {
      max-commands-in-flight = 10000
    }
    index-service {
      max-transactions-in-memory-fan-out-buffer-size = 2000 // keep 20s of transactions in memory instead of 10s
    }
  }
  sequencer-client {
    maximum-in-flight-event-batches = 60
  }
  ledger-api.postgres-data-source.synchronous-commit = off
  replication {
    enabled = ${PARTICIPANT_HA}
  }
}
