import BuildCommon.{CommunityProjects, DamlProjects}

BuildCommon.sbtSettings

lazy val `community-app` = CommunityProjects.`community-app`
lazy val `community-app-base` = CommunityProjects.`community-app-base`
lazy val `community-base` = CommunityProjects.`community-base`
lazy val `community-common` = CommunityProjects.`community-common`
lazy val `community-synchronizer` = CommunityProjects.`community-synchronizer`
lazy val `community-participant` = CommunityProjects.`community-participant`
lazy val `community-admin-api` = CommunityProjects.`community-admin-api`
lazy val `community-testing` = CommunityProjects.`community-testing`
lazy val `community-integration-testing` = CommunityProjects.`community-integration-testing`
lazy val `community-integration-testing-lib` = CommunityProjects.`community-integration-testing-lib`
lazy val `daml-script-tests` = CommunityProjects.`daml-script-tests`
lazy val microbench = CommunityProjects.microbench
lazy val `performance-driver` = CommunityProjects.`performance-driver`
lazy val performance = CommunityProjects.performance
lazy val blake2b = CommunityProjects.blake2b
lazy val `slick-fork` = CommunityProjects.`slick-fork`
lazy val `magnolify-addon` = CommunityProjects.`magnolify-addon`
lazy val `scalatest-addon` = CommunityProjects.`scalatest-addon`
lazy val `util-external` = CommunityProjects.`util-external`
lazy val `util-observability` = CommunityProjects.`util-observability`
lazy val `sequencer-driver-api` = CommunityProjects.`sequencer-driver-api`
lazy val `sequencer-driver-api-conformance-tests` =
  CommunityProjects.`sequencer-driver-api-conformance-tests`
lazy val `sequencer-driver-lib` = CommunityProjects.`sequencer-driver-lib`
lazy val `reference-sequencer-driver` = CommunityProjects.`reference-sequencer-driver`
lazy val `wartremover-extension` = CommunityProjects.`wartremover-extension`
lazy val `wartremover-annotations` = CommunityProjects.`wartremover-annotations`
lazy val `google-common-protos-scala` = DamlProjects.`google-common-protos-scala`
lazy val `ledger-api-value` = DamlProjects.`ledger-api-value`
lazy val `ledger-api-proto` = DamlProjects.`ledger-api-proto`
lazy val `ledger-api-scala` = DamlProjects.`ledger-api-scala`
lazy val `bindings-java` = DamlProjects.`bindings-java`
lazy val `ledger-common` = CommunityProjects.`ledger-common`
lazy val `ledger-common-dars` = CommunityProjects.`ledger-common-dars`
lazy val `ledger-common-dars-lf-v2-dev` = CommunityProjects.`ledger-common-dars-lf-v2-dev`
lazy val `ledger-common-dars-lf-v2-1` = CommunityProjects.`ledger-common-dars-lf-v2-1`
lazy val `base-errors` = CommunityProjects.`base-errors`
lazy val `daml-jwt` = DamlProjects.`daml-jwt`
lazy val `daml-tls` = CommunityProjects.`daml-tls`
lazy val `dam-grpc-utils` = CommunityProjects.`daml-grpc-utils`
lazy val `daml-adjustable-clock` = CommunityProjects.`daml-adjustable-clock`
lazy val `kms-driver-api` = CommunityProjects.`kms-driver-api`
lazy val `kms-driver-testing` = CommunityProjects.`kms-driver-testing`
lazy val `kms-driver-testing-lib` = CommunityProjects.`kms-driver-testing-lib`
lazy val `aws-kms-driver` = CommunityProjects.`aws-kms-driver`
lazy val `mock-kms-driver` = CommunityProjects.`mock-kms-driver`
lazy val `transcode-schema` = CommunityProjects.`transcode-schema`
lazy val `transcode-daml-lf` = CommunityProjects.`transcode-daml-lf`
lazy val `transcode-codec-json` = CommunityProjects.`transcode-codec-json`
lazy val `transcode-codec-proto-java` = CommunityProjects.`transcode-codec-proto-java`
lazy val `transcode-codec-proto-scala` = CommunityProjects.`transcode-codec-proto-scala`
lazy val `transcode-daml-examples` = CommunityProjects.`transcode-daml-examples`
lazy val `transcode-test-conformance` = CommunityProjects.`transcode-test-conformance`
lazy val `transcode-test-utils` = CommunityProjects.`transcode-test-utils`
lazy val `ledger-api-core` = CommunityProjects.`ledger-api-core`
lazy val `ledger-json-api` = CommunityProjects.`ledger-json-api`
lazy val `ledger-json-client` = CommunityProjects.`ledger-json-client`
lazy val `ledger-api-tools` = CommunityProjects.`ledger-api-tools`
lazy val `ledger-api-string-interning-benchmark` =
  CommunityProjects.`ledger-api-string-interning-benchmark`
lazy val `ledger-api-bench-tool` = CommunityProjects.`ledger-api-bench-tool`
lazy val `ledger-test-tool-suites-2-1` = CommunityProjects.`ledger-test-tool-suites-2-1`
lazy val `ledger-test-tool-suites-2-dev` = CommunityProjects.`ledger-test-tool-suites-2-dev`
lazy val `ledger-test-tool-2-1` = CommunityProjects.`ledger-test-tool-2-1`
lazy val `ledger-test-tool-2-dev` = CommunityProjects.`ledger-test-tool-2-dev`
lazy val `conformance-testing` = CommunityProjects.`conformance-testing`
lazy val `upgrading-integration-tests` =
  CommunityProjects.`upgrading-integration-tests`

lazy val `scalatest-utils` = DamlProjects.`scalatest-utils`
lazy val `scala-utils` = DamlProjects.`scala-utils`
lazy val `nonempty` = DamlProjects.`nonempty`
lazy val `nonempty-cats` = DamlProjects.`nonempty-cats`
lazy val `rs-grpc-bridge` = DamlProjects.`rs-grpc-bridge`
lazy val `rs-grpc-pekko` = DamlProjects.`rs-grpc-pekko`
lazy val `logging-entries` = DamlProjects.`logging-entries`
lazy val `contextualized-logging` = DamlProjects.`contextualized-logging`
lazy val `daml-resources` = DamlProjects.`daml-resources`
lazy val `resources-pekko` = DamlProjects.`resources-pekko`
lazy val `resources-grpc` = DamlProjects.`resources-grpc`
lazy val `ledger-resources` = DamlProjects.`ledger-resources`
lazy val `timer-utils` = DamlProjects.`timer-utils`
lazy val crypto = DamlProjects.crypto
lazy val `safe-proto` = DamlProjects.`safe-proto`
lazy val nameof = DamlProjects.nameof
lazy val `testing-utils` = DamlProjects.`testing-utils`
lazy val `grpc-test-utils` = DamlProjects.`grpc-test-utils`
lazy val `rs-grpc-testing-utils` = DamlProjects.`rs-grpc-testing-utils`
lazy val `test-evidence-tag` = DamlProjects.`test-evidence-tag`
lazy val `test-evidence-generator` = DamlProjects.`test-evidence-generator`
lazy val `test-evidence-scalatest` = DamlProjects.`test-evidence-scalatest`
lazy val `sample-service` = DamlProjects.`sample-service`
lazy val `ports` = DamlProjects.`ports`
lazy val `http-test-utils` = DamlProjects.`http-test-utils`
lazy val `concurrent` = DamlProjects.`concurrent`
lazy val `executors` = DamlProjects.`executors`
lazy val `observability-metrics` = DamlProjects.`observability-metrics`
lazy val `observability-tracing` = DamlProjects.`observability-tracing`
lazy val `observability-pekko-http-metrics` = DamlProjects.`observability-pekko-http-metrics`
lazy val `daml-lf-data` = DamlProjects.`daml-lf-data`
lazy val `daml-lf-repl` = DamlProjects.`daml-lf-repl`
lazy val `daml-lf-ide-ledger` = DamlProjects.`daml-lf-ide-ledger`
lazy val `daml-lf-language` = DamlProjects.`daml-lf-language`
lazy val `daml-lf-transaction` = DamlProjects.`daml-lf-transaction`
lazy val `daml-lf-archive` = DamlProjects.`daml-lf-archive`
lazy val `daml-lf-stable-packages` = DamlProjects.`daml-lf-stable-packages`
lazy val `daml-lf-validation` = DamlProjects.`daml-lf-validation`
lazy val `daml-lf-snapshot-proto` = DamlProjects.`daml-lf-snapshot-proto`
lazy val `daml-lf-snapshot` = DamlProjects.`daml-lf-snapshot`
lazy val `daml-lf-interpreter` = DamlProjects.`daml-lf-interpreter`
lazy val `daml-lf-interpreter-bench` = DamlProjects.`daml-lf-interpreter-bench`
lazy val `daml-lf-engine` = DamlProjects.`daml-lf-engine`
lazy val `daml-lf-parser` = DamlProjects.`daml-lf-parser`
lazy val `daml-lf-encoder` = DamlProjects.`daml-lf-encoder`
lazy val `daml-lf-archive-encoder` = DamlProjects.`daml-lf-archive-encoder`
lazy val `daml-lf-api-type-signature` = DamlProjects.`daml-lf-api-type-signature`
lazy val `daml-lf-tests` = DamlProjects.`daml-lf-tests`

lazy val root = (project in file("."))
  .disablePlugins(WartRemover)
  .aggregate((CommunityProjects.allProjects ++ DamlProjects.allProjects).toSeq.map(_.project)*)
