-- Traffic enforcement tables
create table par_traffic_enforcement_event
(
    -- Increasing sequence number for each event
    -- This is used to provide a total ordering of events
    sequence_nb  bigint generated always as identity,
    -- Event source is a small integer that identifies the source of the event (e.g: 0 == LEDGER_API, 1 = TEA_API)
    event_source smallint            not null,
    -- Event type is a small integer that identifies the type of event (e.g 0 == USAGE for standard traffic usage)
    event_type   smallint            not null,
    -- Event ID is a unique identifier per event_source, it is used for event deduplication
    event_id     varchar collate "C" not null,
    -- Account ID is the identifier of the account that the event applies to
    account_id   varchar collate "C" not null,
    -- Amount is the amount of traffic tied to the event, it can be positive or negative.
    -- The actual semantics depend on the event type.
    amount       bigint              not null,
    -- Timestamp when the event was recorded
    -- Critically this is NOT the record time of a transaction. It is generated by the database.
    -- Note that it is possible for events to have timestamps reversed compared to their sequence number
    timestamp    bigint              not null,
    -- Events are unique per (event_source, event_id).
    primary key (event_source, event_id)
);

-- For fast querying by sequence number
create index idx_event_sequence on par_traffic_enforcement_event (sequence_nb);
-- For fast querying by account ID, event type and timestamp
create index account_id_timestamp_index on par_traffic_enforcement_event (account_id, event_type, timestamp);

create or replace view debug.par_traffic_enforcement_event as
select
    sequence_nb,
    event_source,
    event_type,
    event_id,
    account_id,
    amount,
    debug.canton_timestamp(timestamp) as timestamp
from par_traffic_enforcement_event;

-- Balance table for each account
-- Contains one row per account, continuously updated with the total debits and credits for that account
-- as events are processed.
create table par_traffic_enforcement_balance
(
    -- Account ID is the identifier of the account that the balance applies to
    account_id        varchar collate "C" not null,
    -- Event sequence number is the sequence number of the last event that was applied to the balance
    event_sequence_nb bigint              not null,
    -- Matches the event_type of the event table. There's one row per account and event type.
    event_type        smallint            not null,
    -- Total debits is the total amount of traffic that has been debited from the account
    total_debits      bigint              not null,
    -- Total credits is the total amount of traffic that has been credited to the account
    total_credits     bigint              not null,
    -- Updated at is the timestamp of the last update to the balance.
    -- It is at least as recent as the timestamp of the last event that was applied to the balance.
    updated_at        bigint              not null,
    -- One event type per account
    primary key (account_id, event_type)
);

create or replace view debug.par_traffic_enforcement_balance as
select
    account_id,
    event_sequence_nb,
    event_type,
    total_debits,
    total_credits,
    debug.canton_timestamp(updated_at) as updated_at
from par_traffic_enforcement_balance;

-- Offset tables used by pekko projection
-- See https://pekko.apache.org/docs/pekko-projection/current/jdbc.html#schema
create table pekko_projection_offset_store
(
    projection_name varchar collate "C" not null,
    projection_key  varchar collate "C" not null,
    current_offset  varchar collate "C" not null,
    manifest        varchar collate "C" not null,
    mergeable       boolean             not null,
    last_updated    bigint              not null,
    primary key (projection_name, projection_key)
);

create or replace view debug.pekko_projection_offset_store as
select
    projection_name,
    projection_key,
    current_offset,
    manifest,
    mergeable,
    last_updated
from pekko_projection_offset_store;

create index projection_name_index on pekko_projection_offset_store (projection_name);

create table pekko_projection_management
(
    projection_name varchar collate "C" not null,
    projection_key  varchar collate "C" not null,
    paused          boolean             not null,
    last_updated    bigint              not null,
    primary key (projection_name, projection_key)
);

create or replace view debug.pekko_projection_management as
select
    projection_name,
    projection_key,
    paused,
    last_updated
from pekko_projection_management;
