-- Traffic enforcement tables

-- Need to drop the view first
drop view debug.par_traffic_enforcement_event;
-- Drop the event table to re-create it from scratch.
-- That's ok because the events were never exposed nor advertised as a supported feature in this release.
-- The balance per account is kept which maintains traffic balance continuity.
drop table par_traffic_enforcement_event;

-- Changes compared to the initial version:
-- - event_type has been repurposed to indicate how to apply the event to the account balance (e.g DELTA_DEBIT, DELTA_CREDIT)
create table par_traffic_enforcement_event
(
    -- Increasing sequence number for each event
    -- This is used to provide a total ordering of events
    sequence_nb  bigint generated always as identity,
    -- Event source is a small integer that identifies the source of the event (e.g: 0 == LEDGER_API_COMPLETIONS, 1 = TEA_API)
    event_source smallint            not null,
    -- Event type identifies how to apply the event to the account balance (e.g CREDIT_DELTA, DEBIT_DELTA)
    event_type   smallint            not null,
    -- Event ID is a unique identifier per event_source, it is used for event deduplication
    event_id     varchar collate "C" not null,
    -- Account ID is the identifier of the account that the event applies to
    account_id   varchar collate "C" not null,
    -- Amount is the amount of traffic tied to the event, it can be positive or negative.
    -- The actual semantics depend on the event_type.
    amount       bigint              not null,
    -- Timestamp when the event was recorded
    -- Critically this is NOT the record time of a transaction. It is generated by the database.
    -- Note that it is possible for events to have timestamps reversed compared to their sequence number
    timestamp    bigint              not null,
    -- Events are unique per (event_source, event_id).
    primary key (event_source, event_id)
);

-- For fast querying by sequence number
create index idx_event_sequence on par_traffic_enforcement_event (sequence_nb);
-- For fast querying by account ID and timestamp
create index account_id_timestamp_index on par_traffic_enforcement_event (account_id, timestamp);

-- Recreate the view
create or replace view debug.par_traffic_enforcement_event as
select sequence_nb,
       event_source,
       event_type,
       event_id,
       account_id,
       amount,
       debug.canton_timestamp(timestamp) as timestamp
from par_traffic_enforcement_event;

-- Now update the par_traffic_enforcement_balance table to remove the event_type column,
-- which is no longer needed there as it now has a different meaning in the event table.

-- Drop the view first
drop view debug.par_traffic_enforcement_balance;

-- 1. Drop the existing composite primary key
ALTER TABLE par_traffic_enforcement_balance
    -- Posgres names the primary key with _pkey suffix by default
    DROP CONSTRAINT par_traffic_enforcement_balance_pkey;

-- 2. Drop the column (this deletes 'event_type' completely)
ALTER TABLE par_traffic_enforcement_balance
    DROP COLUMN event_type;

-- 3. Re-add the primary key using only account_id
ALTER TABLE par_traffic_enforcement_balance
    ADD PRIMARY KEY (account_id);

-- Recreate the view without event_type
create or replace view debug.par_traffic_enforcement_balance as
select
    account_id,
    event_sequence_nb,
    total_debits,
    total_credits,
    debug.canton_timestamp(updated_at) as updated_at
from par_traffic_enforcement_balance;
