canton {
  sequencers {
    sequencer1 {
      public-api.port = 8031
      admin-api.port = 8032
      sequencer {
        type = reference
        config.storage.type = memory
      }
      storage.type = memory
    }
  }

  mediators {
    mediator1 {
      admin-api.port = 8033
    }
  }
}
