canton {
  sequencers {
    sequencer2 {
      public-api.port = 8041
      admin-api.port = 8042
      sequencer {
        type = reference
        config.storage.type = memory
      }
      storage.type = memory
    }
  }

  mediators {
    mediator2 {
      admin-api.port = 8043
    }
  }
}
