#
# Copyright 2022 Digital Asset (Switzerland) GmbH and/or its affiliates
#
# SPDX-License-Identifier: Apache-2.0
#
version: '3'

# ------------------------------------------------------------
# demo participant deployment
#
# this deployment sets up
# - postgres database
# - canton participant
# - trigger service
# - json api
# ------------------------------------------------------------

volumes:
  pgdata:

services:

  postgres.database:
    image: "postgres:11"
    ports:
      - "${BASE_PORT:-40}32:5432"
    environment:
      - POSTGRES_USER=canton
      - POSTGRES_PASSWORD=supersafe
      - POSTGRES_DB=participant1
    command: [
      "-c" , "config_file=/data/utils/postgresql.conf"
    ]
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./data/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./data:/data:cached

  connect.cleanup:
    image: digitalasset/canton-${CANTON_TYPE:-open-source}:${CANTON_VERSION:-latest}
    entrypoint: []
    command: sh ./utils/cleanup.sh
    volumes:
      - ./data/utils:/canton/utils
      - ./data/shared:/canton/shared
      - ./data/logs:/canton/logs

  connect.node:
    image: digitalasset/canton-${CANTON_TYPE:-open-source}:${CANTON_VERSION:-latest}
    ports:
      - "${BASE_PORT:-40}11:10011"
      - "${BASE_PORT:-40}12:10012"
    tty: true
    environment:
      - POSTGRES_HOST=postgres.database
      - POSTGRES_USER=canton
      - POSTGRES_PASSWORD=supersafe
      - CANTON_AUTO_APPROVE_AGREEMENTS=yes
      - CANTON_ALLOCATE_PARTIES=${CANTON_ALLOCATE_PARTIES:-alice;bob}
      - CANTON_CONNECT_DOMAINS=${CANTON_CONNECT_DOMAINS:-mydomain#http://localhost:10018}
      - JAVA_OPTS="-Xmx3G"
    command: ["daemon", "--log-profile=container", "--log-file-name=./data/logs/canton.log",
      "-c" ,"data/canton/config.canton",
      "-c" ,"examples/03-advanced-configuration/storage/postgres.conf",
      "-c" , "${CANTON_CONFIG:-data/canton/participant.conf,data/canton/domain.conf}",
      "--bootstrap=data/canton/bootstrap.canton"]
    volumes:
      - ./data:/canton/data
    links:
      - postgres.database
    depends_on:
      - postgres.database
      - connect.cleanup

  connect.navigator:
    image: digitalasset/daml-sdk:${SDK_VERSION:-2.0.0-snapshot.20220127.9042.0.4038d0a7}
    environment:
      - _JAVA_OPTIONS="-Dlogback.configurationFile=./data/utils/sdk-logback.xml"
      - LOG_FILE=./data/logs/navigator.log
    entrypoint: []
    command: sh -c "./data/utils/wait_for_file.sh data/shared/parties.txt && daml ledger navigator --host connect.node --port 10011 --port ${BASE_PORT:-40}00 -c ./data/utils/navigator_dummy_config_remove_after_daml_1_9_0.conf"
    ports:
      - "${BASE_PORT:-40}00:${BASE_PORT:-40}00"
    volumes:
      - ./data:/home/daml/data
    depends_on:
      - connect.node
    links:
      - connect.node

  connect.json:
    image: digitalasset/daml-sdk:${SDK_VERSION:-2.0.0-snapshot.20220127.9042.0.4038d0a7}
    ports:
      - "${BASE_PORT:-40}01:4001"
    environment:
      - _JAVA_OPTIONS="-Dlogback.configurationFile=./data/utils/sdk-logback.xml"
      - LOG_FILE=./data/logs/json.log
    entrypoint: []
    command: sh -c "./data/utils/wait_for_file.sh data/shared/parties.txt && daml json-api --ledger-host connect.node --ledger-port 10011 --address 0.0.0.0 --port-file ./data/shared/json.port --http-port 4001 --allow-insecure-tokens --static-content \"prefix=static,directory=/home/daml/data/static-content\" --query-store-jdbc-config \"driver=org.postgresql.Driver,url=jdbc:postgresql://postgres.database:5432/jsonapi?&ssl=false,user=canton,password=supersafe,start-mode=create-and-start\""
    volumes:
      - ./data:/home/daml/data
    depends_on:
      - connect.node
    links:
      - connect.node

  connect.trigger:
    image: digitalasset/daml-sdk:${SDK_VERSION:-2.0.0-snapshot.20220127.9042.0.4038d0a7}
    environment:
      - _JAVA_OPTIONS="-Dlogback.configurationFile=./data/utils/sdk-logback.xml"
      - LOG_FILE=./data/logs/triggers.log
    ports:
      - "${BASE_PORT:-40}02:4002"
    entrypoint: []
    command: sh -c "./data/utils/wait_for_file.sh data/shared/parties.txt && daml trigger-service --ledger-host connect.node --ledger-port 10011 --address 0.0.0.0 --http-port 4002 --jdbc \"driver=org.postgresql.Driver,url=jdbc:postgresql://postgres.database:5432/triggers?&ssl=false,user=canton,password=supersafe\""
    volumes:
      - ./data:/home/daml/data
    depends_on:
      - connect.node
    links:
      - connect.node
