include required("performance/shared.conf")
include required("performance/postgres/persistence.conf")
include required("performance/topology/basesequencer.conf")
include required("performance/topology/basesequencer-reference.conf")
include required("performance/topology/basemediator.conf")

canton {
  sequencers {
    sequencer = ${_basesequencer}
    sequencer.sequencer = ${_sequencer}
    sequencer {
      admin-api {
        address = "0.0.0.0"
        port = 10002
      }
      public-api {
        address = "0.0.0.0"
        port = 10003
      }
      storage.config.properties.databaseName = ${?DBPREFIX}sequencer
      storage.config.properties.currentSchema = ${?DBPREFIX}sequencer

    }
  }

  mediators {
    mediator = ${_basemediator}
    mediator {
      admin-api {
        address = "0.0.0.0"
        port = 10001
      }
      storage.config.properties.databaseName = ${?DBPREFIX}mediator
      storage.config.properties.currentSchema = ${?DBPREFIX}mediator
    }
  }
}
