// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package com.digitalasset.canton.synchronizer.sequencer

import com.daml.nonempty.NonEmpty
import com.digitalasset.canton.concurrent.FutureSupervisor
import com.digitalasset.canton.config.RequireTypes.{NonNegativeInt, PositiveInt}
import com.digitalasset.canton.config.{CachingConfigs, DefaultProcessingTimeouts, TopologyConfig}
import com.digitalasset.canton.crypto.{SigningPublicKey, SynchronizerCryptoClient}
import com.digitalasset.canton.data.CantonTimestamp
import com.digitalasset.canton.sequencing.protocol.AggregationRule
import com.digitalasset.canton.synchronizer.HasTopologyTransactionTestFactory
import com.digitalasset.canton.synchronizer.sequencer.InFlightAggregation.{
  AggregationStuffing,
  AlreadyDelivered,
}
import com.digitalasset.canton.time.Clock
import com.digitalasset.canton.topology.client.StoreBasedSynchronizerTopologyClient
import com.digitalasset.canton.topology.processing.{ApproximateTime, EffectiveTime, SequencedTime}
import com.digitalasset.canton.topology.store.TopologyStoreId.SynchronizerStore
import com.digitalasset.canton.topology.store.memory.InMemoryTopologyStore
import com.digitalasset.canton.topology.store.{NoPackageDependencies, ValidatedTopologyTransaction}
import com.digitalasset.canton.topology.transaction.SignedTopologyTransaction.GenericSignedTopologyTransaction
import com.digitalasset.canton.topology.transaction.TopologyTransaction.TxHash
import com.digitalasset.canton.topology.transaction.{MediatorSynchronizerState, OwnerToKeyMapping}
import com.digitalasset.canton.topology.{
  MediatorId,
  PhysicalSynchronizerId,
  SequencerId,
  UniqueIdentifier,
}
import com.digitalasset.canton.version.ProtocolVersion
import com.digitalasset.canton.{
  BaseTest,
  HasExecutionContext,
  TestEssentials,
  TestPredicateFiltersFixtureAnyWordSpec,
}
import org.scalatest.Outcome
import org.scalatest.wordspec.FixtureAnyWordSpec

import scala.collection.immutable.SortedMap

/** Test our aggregation logic
  *
  * We test aggregating signatures. We can assume that all supplied signatures were valid at the
  * point when they were added.
  *
  * They may no longer be valid at the point of aggregation, due to key or member expiration, but we
  * should still be able to aggregate them, and they should not count towards delivery.
  */
class InFlightAggregationTest
    extends FixtureAnyWordSpec
    with BaseTest
    with TestPredicateFiltersFixtureAnyWordSpec
    with TestEssentials
    with HasTopologyTransactionTestFactory
    with HasExecutionContext {

  private object SyncCrypto {

    val synchronizerId: PhysicalSynchronizerId =
      topologyTransactionFactory.synchronizerId1.toPhysical
    val sequencer1: SequencerId = topologyTransactionFactory.sequencer1
    val topologyStore =
      new InMemoryTopologyStore(
        SynchronizerStore(synchronizerId),
        predecessor = None,
        testedProtocolVersion,
        loggerFactory,
        timeouts,
      )

    import topologyTransactionFactory.SigningKeys.*

    val ts0 = CantonTimestamp.Epoch
    val ts1 = CantonTimestamp.Epoch.plusSeconds(1)
    val ts2 = CantonTimestamp.Epoch.plusSeconds(2)
    val ts3 = CantonTimestamp.Epoch.plusSeconds(3)
    val mediator1 = MediatorId(UniqueIdentifier.tryCreate("one", "ns"))
    val mediator2 = MediatorId(UniqueIdentifier.tryCreate("two", "ns"))
    val mediator3 = MediatorId(UniqueIdentifier.tryCreate("three", "ns"))
    private def mkOkm(m: MediatorId, k: SigningPublicKey, serial: PositiveInt = PositiveInt.one) =
      topologyTransactionFactory.mkAdd(
        OwnerToKeyMapping.tryCreate(m, NonEmpty(Seq, k)),
        k,
        serial = serial,
      )
    val okm1 = mkOkm(mediator1, key1)
    val okm1b = mkOkm(mediator1, key4, serial = PositiveInt.two)
    val okm2 = mkOkm(mediator2, key2)
    val okm3 = mkOkm(mediator3, key3)
    private def mkMds(mediators: Seq[MediatorId]) =
      topologyTransactionFactory.mkAdd(
        MediatorSynchronizerState
          .create(
            synchronizerId.logical,
            group = NonNegativeInt.zero,
            threshold = PositiveInt.two,
            active = mediators,
            observers = Seq.empty,
          )
          .value
      )
    val mds1 = mkMds(Seq(mediator1, mediator2))
    val mds2 = mkMds(Seq(mediator1, mediator2, mediator3))
    val mds3 = mkMds(Seq(mediator2, mediator3))

    // these are signatures that we can use in our test, generated by different keys
    val sig1 = okm1.signatures.map(_.signature).head1
    val sig2 = okm2.signatures.map(_.signature).head1
    val sig3 = okm3.signatures.map(_.signature).head1
    val sig4 = okm1b.signatures.map(_.signature).head1

    private def store(
        ts: CantonTimestamp,
        add: Seq[GenericSignedTopologyTransaction],
        remove: Seq[GenericSignedTopologyTransaction] = Seq.empty,
    ) =
      topologyStore
        .update(
          SequencedTime(ts),
          EffectiveTime(ts),
          removals =
            remove.map(tx => tx.mapping.uniqueKey -> (Some(tx.serial), Set.empty[TxHash])).toMap,
          additions = add.map(ValidatedTopologyTransaction(_, rejectionReason = None)),
        )
        .futureValueUS

    store(ts0, add = Seq(okm1, okm2, okm3, mds1))
    store(ts1, add = Seq(okm1b), remove = Seq(okm1))
    store(ts2, add = Seq(mds2), remove = Seq(mds1))
    store(ts3, add = Seq(mds3), remove = Seq(mds2))

    val topologyClient = new StoreBasedSynchronizerTopologyClient(
      mock[Clock],
      defaultStaticSynchronizerParameters,
      topologyStore,
      NoPackageDependencies,
      topologyConfig = TopologyConfig(),
      DefaultProcessingTimeouts.testing,
      FutureSupervisor.Noop,
      loggerFactory,
    )
    topologyClient.updateHead(
      SequencedTime(ts3.immediateSuccessor),
      EffectiveTime(ts3.immediateSuccessor),
      ApproximateTime(ts3.immediateSuccessor),
    )
    val cryptoApi = SynchronizerCryptoClient.create(
      member = sequencer1,
      synchronizerId.logical,
      topologyClient,
      defaultStaticSynchronizerParameters,
      topologyTransactionFactory.syncCryptoClient.crypto,
      CachingConfigs.defaultPublicKeyConversionCache,
      DefaultProcessingTimeouts.testing,
      FutureSupervisor.Noop,
      loggerFactory,
    )
  }
  import SyncCrypto.*

  private val maxTs = CantonTimestamp.Epoch.plusSeconds(5)

  class InFlightAggregationTestFixture {
    val empty = new InFlightAggregation(
      aggregatedSenders = SortedMap.empty,
      maxSequencingTimestamp = maxTs,
      rule = AggregationRule.activeMediators(
        NonEmpty.mk(Seq, mediator1, mediator2, mediator3),
        groupIndex = NonNegativeInt.zero,
        threshold = PositiveInt.two,
        protocolVersion = testedProtocolVersion,
      ),
      cachedDeliveredAt = Some(None),
    )

    def aggregate(
        agg: InFlightAggregation,
        sender: AggregatedSender,
        tsp: CantonTimestamp,
    ): InFlightAggregation =
      agg.tryAggregate(sender, cryptoApi.snapshot(tsp).futureValueUS).futureValueUS.value

    def boo() = fail("booh")

  }

  override type FixtureParam = InFlightAggregationTestFixture

  override def withFixture(test: OneArgTest): Outcome = {
    val f: FixtureParam = new InFlightAggregationTestFixture()
    withFixture(test.toNoArgTest(f))
  }

  "complete fresh" in { ff =>
    val tsp = ts0.immediateSuccessor
    val fst = AggregatedSender(mediator1, Seq(Seq(sig1)), tsp)
    val snd = AggregatedSender(mediator2, Seq(Seq(sig2)), tsp)
    val fstAgg = ff.aggregate(ff.empty, fst, tsp)
    fstAgg.tryIsDeliveredAt shouldBe empty
    val sndAgg = ff.aggregate(fstAgg, snd, tsp)
    sndAgg.tryIsDeliveredAt should not be empty
  }
  "bounce already delivered" in { ff =>
    val tsp = ts2.immediateSuccessor
    val fst = AggregatedSender(mediator1, Seq(Seq(sig4)), tsp)
    val snd = AggregatedSender(mediator2, Seq(Seq(sig2)), tsp)
    // should bounce as two are enough
    val trd = AggregatedSender(mediator3, Seq(Seq(sig3)), tsp)

    val step1 = ff.aggregate(ff.empty, fst, tsp)
    val step2 = ff.aggregate(step1, snd, tsp)
    val step3 = step2.tryAggregate(trd, cryptoApi.snapshot(tsp).futureValueUS).futureValueUS

    step2.tryIsDeliveredAt should not be empty
    step3.left.value shouldBe AlreadyDelivered(tsp)
  }

  "reject stuffing" in { ff =>
    val tsp = ts2.immediateSuccessor
    val fst = AggregatedSender(mediator1, Seq(Seq(sig4)), tsp)
    // we already have mediator1
    val snd = AggregatedSender(mediator1, Seq(Seq(sig1)), tsp)
    val step1 = ff.aggregate(ff.empty, fst, tsp)
    val step2 = step1.tryAggregate(snd, cryptoApi.snapshot(tsp).futureValueUS).futureValueUS
    step2.left.value shouldBe AggregationStuffing(mediator1, tsp)
  }
  "remove expired key" onlyRunWithOrGreaterThan ProtocolVersion.v35 in { ff =>
    val tsp = ts2.immediateSuccessor
    // key1 will expire at ts1
    val fst = AggregatedSender(mediator1, Seq(Seq(sig1)), tsp)
    val snd = AggregatedSender(mediator2, Seq(Seq(sig2)), tsp)
    val res = ff.aggregate(ff.aggregate(ff.empty, fst, tsp), snd, tsp)
    res.tryIsDeliveredAt shouldBe empty
  }
  "remove expired member" onlyRunWithOrGreaterThan ProtocolVersion.v35 in { ff =>
    val tsp = ts3.immediateSuccessor
    // mediator1 is gone at ts3
    val fst = AggregatedSender(mediator1, Seq(Seq(sig4)), ts2.immediateSuccessor)
    val snd = AggregatedSender(mediator2, Seq(Seq(sig2)), tsp)
    val trd = AggregatedSender(mediator3, Seq(Seq(sig3)), tsp)
    val step1 = ff.aggregate(ff.empty, fst, ts2.immediateSuccessor)
    val step2 = ff.aggregate(step1, snd, tsp)
    val step3 = ff.aggregate(step2, trd, tsp)
    step1.tryIsDeliveredAt shouldBe empty
    step2.tryIsDeliveredAt shouldBe empty
    step3.tryIsDeliveredAt shouldBe Some(tsp)
  }

  "recompute after crash" in { ff =>
    val tsp = ts2.immediateSuccessor
    val fst = AggregatedSender(mediator1, Seq(Seq(sig4)), tsp)
    val snd = AggregatedSender(mediator2, Seq(Seq(sig2)), tsp)
    val res = ff.aggregate(ff.aggregate(ff.empty, fst, tsp), snd, tsp)
    res.tryIsDeliveredAt should not be empty
    val dropped = res
      .copy(cachedDeliveredAt = None)
      .prepareForNewAggregation(
        tsp,
        Some(ts2),
        cryptoApi,
      )
      .futureValueUS
    dropped.tryIsDeliveredAt shouldBe res.tryIsDeliveredAt
  }

}
