// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package com.digitalasset.canton.integration.tests.modelbased

import com.digitalasset.canton.BaseTest.UnsupportedExternalPartyTest.NuckSupport
import com.digitalasset.canton.integration.util.PartiesAllocator
import com.digitalasset.canton.integration.{
  CommunityIntegrationTest,
  EnvironmentDefinition,
  SharedEnvironment,
}
import com.digitalasset.canton.testing.modelbased.ast.Concrete
import com.digitalasset.canton.testing.modelbased.runner.CantonInterpreter
import com.digitalasset.canton.testing.modelbased.syntax.Parser
import com.digitalasset.canton.version.ProtocolVersion

/** The examples in this file were largely generated by the ModelBasedCantonIntegrationTest that at
  * the time of generation were causing problems for the implementation.
  */
// TODO(#31527): SPM enable overnight run by moving to com/digitalasset/canton/integration/tests
final class NuckCantonIntegrationTest extends CommunityIntegrationTest with SharedEnvironment {

  override lazy val environmentDefinition: EnvironmentDefinition =
    EnvironmentDefinition.P3_S1M1
      .withSetup { implicit env =>
        import env.*
        participants.all.synchronizers.connect_local(sequencer1, alias = daName)

        cantonInterpreter = CantonInterpreter.initializeAndUpload(
          participants = participants.all.toIndexedSeq,
          synchronizerId = daId,
          allocateParties =
            (ps, newParties, targetTopology) => PartiesAllocator(ps)(newParties, targetTopology),
        )
      }

  private var cantonInterpreter: CantonInterpreter = _

  def run(scenario: Concrete.Scenario): Unit =
    cantonInterpreter.runAndProject(scenario) match {
      case Left(error) =>
        fail(error)
      case Right(projections) =>
        assert(projections.nonEmpty)
    }

  "Canton" should {

    "run a simple scenario without keys" onlyRunWithOrGreaterThan ProtocolVersion.v35 andWhen onlyLocalParty(
      NuckSupport
    ) in { _ =>
      val scenario = Parser.assertParseScenario("""
            |Scenario
            |  Topology
            |    Participant 0 pkgs={0} parties={1}
            |  Ledger
            |    Commands participant=0 actAs={1} disclosures=[]
            |      Create 0 sigs={1} obs={}
            |    Commands participant=0 actAs={1} disclosures=[]
            |      Exercise Consuming 0 ctl={1} cobs={}
            |""".stripMargin)

      run(scenario)
    }

    "run a simple scenario involving LookupByKey" onlyRunWithOrGreaterThan ProtocolVersion.v35 andWhen onlyLocalParty(
      NuckSupport
    ) in { _ =>
      val scenario = Parser.assertParseScenario("""
            |Scenario
            |  Topology
            |    Participant 0 pkgs={0} parties={1}
            |  Ledger
            |    Commands participant=0 actAs={1} disclosures=[]
            |      Create 0 sigs={1} obs={}
            |    Commands participant=0 actAs={1} disclosures=[]
            |      CreateWithKey 1 key=(1, {1}) sigs={1} obs={}
            |      Exercise NonConsuming 0 ctl={1} cobs={}
            |        QueryByKey [1] exhaustive=true
            |""".stripMargin)

      run(scenario)
    }

    "run a complex scenario involving LookupByKey" onlyRunWithOrGreaterThan ProtocolVersion.v35 andWhen onlyLocalParty(
      NuckSupport
    ) in { _ =>
      val scenario = Parser.assertParseScenario("""
          |Scenario
          |  Topology
          |    Participant 0 pkgs={0} parties={1,3}
          |    Participant 1 pkgs={0} parties={1,2,3}
          |  Ledger
          |    Commands participant=1 actAs={1,2} disclosures=[]
          |      Create 0 pkg=0 sigs={1,2} obs={1,2,3}
          |      CreateWithKey 1 key=(4, {1}) sigs={1} obs={1,2,3}
          |      CreateWithKey 2 pkg=0 key=(2, {2}) sigs={1,2} obs={1,3}
          |    Commands participant=1 actAs={1,2,3} disclosures=[]
          |      ExerciseByKey NonConsuming 2 pkg=0 ctl={1} cobs={1,2,3}
          |        LookupByKey Success 2
          |      ExerciseByKey NonConsuming 1 ctl={3} cobs={2,3}
          |        Exercise Consuming 0 ctl={3} cobs={}
          |          FetchByKey 2
          |          Fetch 1
          |          CreateWithKey 3 key=(1, {3}) sigs={1,3} obs={}
          |          ExerciseByKey NonConsuming 3 ctl={2} cobs={1}
          |            Create 4 sigs={1} obs={1}
          |        ExerciseByKey Consuming 2 ctl={3} cobs={1}
          |      CreateWithKey 5 key=(3, {2}) sigs={1,2} obs={2,3}
          |      ExerciseByKey Consuming 5 pkg=0 ctl={3} cobs={1,2}
          |        LookupByKey Success 3
          |""".stripMargin)

      run(scenario)
    }

    "run create/exercise" onlyRunWithOrGreaterThan ProtocolVersion.v35 andWhen onlyLocalParty(
      NuckSupport
    ) in { _ =>
      run(Parser.assertParseScenario("""
        |Scenario
        |  Topology
        |    Participant 0 pkgs={0} parties={1}
        |  Ledger
        |    Commands participant=0 actAs={1} disclosures=[]
        |      Create 0 sigs={1} obs={}
        |    Commands participant=0 actAs={1} disclosures=[]
        |      Exercise Consuming 0 ctl={1} cobs={}
        |""".stripMargin))
    }

    "run create with key/exercise by key" onlyRunWithOrGreaterThan ProtocolVersion.v35 andWhen onlyLocalParty(
      NuckSupport
    ) in { _ =>
      val scenario = Parser.assertParseScenario("""
        |Scenario
        |  Topology
        |    Participant 0 pkgs={0} parties={3}
        |  Ledger
        |    Commands participant=0 actAs={3} disclosures=[]
        |      CreateWithKey 1 key=(2, {3}) sigs={3} obs={}
        |      ExerciseByKey Consuming 1 ctl={3} cobs={}
        |""".stripMargin)
      run(scenario)
    }

    "run create with key/query by key" onlyRunWithOrGreaterThan ProtocolVersion.v35 andWhen onlyLocalParty(
      NuckSupport
    ) in { _ =>
      val scenario = Parser.assertParseScenario("""
        |Scenario
        |  Topology
        |    Participant 0 pkgs={0} parties={1}
        |  Ledger
        |    Commands participant=0 actAs={1} disclosures=[]
        |      Create 0 sigs={1} obs={}
        |    Commands participant=0 actAs={1} disclosures=[]
        |      CreateWithKey 1 key=(1, {1}) sigs={1} obs={}
        |      Exercise NonConsuming 0 ctl={1} cobs={}
        |        QueryByKey [1] exhaustive=true
        |""".stripMargin)

      run(scenario)
    }

    // TODO(#31527): SPM why does this test take so long (1 min, vs 1 sec for the other tests)
    "return contracts in observed order" onlyRunWithOrGreaterThan ProtocolVersion.v35 andWhen onlyLocalParty(
      NuckSupport
    ) in { _ =>
      val scenario = Parser.assertParseScenario("""
        |Scenario
        |  Topology
        |    Participant 0 pkgs={0} parties={2,3}
        |  Ledger
        |    Commands participant=0 actAs={2} disclosures=[]
        |      CreateWithKey 0 key=(1, {2}) sigs={2} obs={}
        |    Commands participant=0 actAs={2,3} disclosures=[]
        |      CreateWithKey 1 key=(1, {2}) sigs={2} obs={}
        |      CreateWithKey 2 key=(1, {2}) sigs={2} obs={}
        |      Exercise NonConsuming 0 ctl={3} cobs={}
        |        QueryByKey [2,1,0] exhaustive=true""".stripMargin)
      run(scenario)
    }

    "consuming exercise by key" onlyRunWithOrGreaterThan ProtocolVersion.v35 andWhen onlyLocalParty(
      NuckSupport
    ) in { _ =>
      val scenario = Parser.assertParseScenario("""
       |Scenario
       |  Topology
       |    Participant 2 pkgs={0} parties={1,3}
       |  Ledger
       |    Commands participant=2 actAs={1,3} disclosures=[]
       |      CreateWithKey 0 key=(1, {1,3}) sigs={1,3} obs={}
       |      CreateWithKey 1 key=(1, {1,3}) sigs={1,3} obs={}
       |      ExerciseByKey Consuming 1 ctl={1} cobs={}
       |        QueryByKey [0] exhaustive=true""".stripMargin)
      run(scenario)
    }

    "key resolutions may reference contract ids outside the core inputs" onlyRunWithOrGreaterThan ProtocolVersion.v35 andWhen onlyLocalParty(
      NuckSupport
    ) in { _ =>
      val scenario = Parser.assertParseScenario("""
          |Scenario
          |  Topology
          |    Participant 0 pkgs={0} parties={1}
          |    Participant 2 pkgs={0} parties={2,3}
          |  Ledger
          |    Commands participant=2 actAs={2,3} disclosures=[]
          |      CreateWithKey 3 key=(1, {2}) sigs={2} obs={}
          |      CreateWithKey 5 key=(1, {2}) sigs={2} obs={}
          |      ExerciseByKey NonConsuming 5 ctl={3} cobs={}
          |        ExerciseByKey NonConsuming 5 ctl={2} cobs={1}
          |          QueryByKey [5,3] exhaustive=false""".stripMargin)
      run(scenario)
    }

    "expired with evidence of key via query by id" onlyRunWithOrGreaterThan ProtocolVersion.v35 andWhen onlyLocalParty(
      NuckSupport
    ) in { _ =>
      val scenario = Parser.assertParseScenario("""
          |Scenario
          |  Topology
          |    Participant 1 pkgs={0} parties={2,3}
          |  Ledger
          |    Commands participant=1 actAs={3} disclosures=[]
          |      CreateWithKey 0 key=(1, {3}) sigs={3} obs={}
          |    Commands participant=1 actAs={2,3} disclosures=[]
          |      CreateWithKey 1 key=(1, {3}) sigs={3} obs={}
          |      ExerciseByKey Consuming 1 ctl={2} cobs={}
          |        Fetch 0""".stripMargin)
      run(scenario)
    }

    "example with keyed contract used by id" onlyRunWithOrGreaterThan ProtocolVersion.v35 andWhen onlyLocalParty(
      NuckSupport
    ) in { _ =>
      val scenario = Parser.assertParseScenario("""
          |Scenario
          |  Topology
          |    Participant 0 pkgs={0} parties={1,2,3}
          |  Ledger
          |    Commands participant=0 actAs={3} disclosures=[]
          |      CreateWithKey 0 key=(1, {3}) sigs={3} obs={}
          |    Commands participant=0 actAs={1,2,3} disclosures=[]
          |      CreateWithKey 1 key=(1, {3}) sigs={1,2,3} obs={1,3}
          |      ExerciseByKey NonConsuming 1 pkg=0 ctl={3} cobs={2,3}
          |        Exercise Consuming 0 ctl={1} cobs={2,3}
          |        Create 2 sigs={2,3} obs={3}
          |        FetchByKey 1
          |        CreateWithKey 3 key=(1, {3}) sigs={2,3} obs={2,3}
          |        Exercise Consuming 2 ctl={1} cobs={3}
          |          QueryByKey [3,1] exhaustive=false
          |          QueryByKey [3,1] exhaustive=true
          |          LookupByKey Failure key=(1, {1,3})
          |          Fetch 3
          |          Exercise NonConsuming 3 ctl={1,3} cobs={1}
          |          ExerciseByKey NonConsuming 3 ctl={1,3} cobs={}
          |            FetchByKey 3
          |            Fetch 3
          |          LookupByKey Success 3""".stripMargin)
      run(scenario)
    }

    "two QueryByKeys for the same key in the same view" onlyRunWithOrGreaterThan ProtocolVersion.v35 andWhen onlyLocalParty(
      NuckSupport
    ) in { _ =>
      val scenario = Parser.assertParseScenario(
        """
                                                  |Scenario
                                                  |  Topology
                                                  |    Participant 0 pkgs={0} parties={1}
                                                  |  Ledger
                                                  |    Commands participant=0 actAs={1} disclosures=[]
                                                  |      Create 0 sigs={1} obs={}
                                                  |      CreateWithKey 4 key=(0, {1}) sigs={1} obs={}
                                                  |      CreateWithKey 3 key=(0, {1}) sigs={1} obs={}
                                                  |      CreateWithKey 2 key=(0, {1}) sigs={1} obs={}
                                                  |      CreateWithKey 1 key=(0, {1}) sigs={1} obs={}
                                                  |    Commands participant=0 actAs={1} disclosures=[]
                                                  |      Exercise NonConsuming 0 ctl={1} cobs={}
                                                  |        QueryByKey [1,2] exhaustive=false
                                                  |        QueryByKey [1,2,3,4] exhaustive=true""".stripMargin
      )
      run(scenario)
    }

  }

}
