post_to_datadog:
  parameters:
    label:
      type: string
    data:
      # List of metric names and values, e.g., "metric1=0.01 metric2=2.32"
      # Metric name and value are separated by "=".
      # List elements are separated by spaces.
      # Values must be floating point numbers.
      type: string
    metric_type:
      type: enum
      enum: ["gauge", "count", "rate"]
      default: gauge
    when:
      type: enum
      enum: ["always", "on_success", "on_fail"]
      default: always
    use_commit_time:
      type: boolean
      default: true
  steps:
    - run:
        name: << parameters.label >>
        when: << parameters.when >>
        command: |
          if [[ -n "<< parameters.data >>" ]]; then
            <<# parameters.use_commit_time >>
            TIMESTAMP=$(git log -1 --pretty=%ct)
            <</ parameters.use_commit_time >>
            <<^ parameters.use_commit_time >>
            TIMESTAMP=$(date +%s)
            <</ parameters.use_commit_time >>
            echo "Timestamp: $TIMESTAMP"
            HASH=$(git log -1 --pretty=%h)
            echo "Commit hash (abbreviated): $HASH"
            TAGS=$(jo -a "branch:$CIRCLE_BRANCH" "hash:$HASH" "workflow:$CIRCLE_WORKFLOW_ID" "job:$CIRCLE_JOB" "build:$CIRCLE_BUILD_NUM" "url:$CIRCLE_BUILD_URL" "container:$CIRCLE_NODE_INDEX")

            ./scripts/ci/post-to-datadog.sh "$TIMESTAMP" << parameters.metric_type >> "$TAGS" << parameters.data >>
          fi

post_benchmark_metrics:
  steps:
    - run:
        name: Read benchmark metrics from test report
        when: always
        command: |
          if cat benchmark_*.dat > benchmark.dat 2> /dev/null ; then
            benchmark="$(cat benchmark.dat | tr '\n' ' ')"
          else
            benchmark=""
          fi

          echo "BENCHMARK=$benchmark"
          echo "export BENCHMARK=\"$benchmark\"" >> $BASH_ENV
    - post_to_datadog:
        label: "Post benchmark metrics to Datadog"
        data: "$BENCHMARK"
        when: always

post_transaction_snapshot_metrics:
  steps:
    - run:
        name: Read transaction snapshot benchmark metrics from JMH test report
        when: always
        command: |
          TIMESTAMP=$(date +%s)
          echo "Timestamp: $TIMESTAMP"
          HASH=$(git log -1 --pretty=%h)
          echo "Commit hash (abbreviated): $HASH"

          for obj in $(jq -c '.[] | {params:.params, primaryMetric:.primaryMetric, secondaryMetrics:.secondaryMetrics}' $BENCHMARKING_RESULT_FILE); do
            CHOICE_NAME=$(echo $obj |jq -r '.params.choiceName'  |sed 's/^[0-9a-fA-F]*://')
            CONTRACT_ID_VERSION=$(echo $obj |jq -r '.params.contractIdVersion')
            GAS_ON=$(echo $obj |jq -r '.params.gasOn')
            BENCHMARK=$(echo $obj |jq -r '.primaryMetric.score')
            STEP_COUNT=$(echo $obj |jq -r '.secondaryMetrics.stepCount.score')
            FETCH_NODE_COUNT=$(echo $obj |jq -r '.secondaryMetrics.fetchNodeCount.score')
            TRANSACTION_NODE_COUNT=$(echo $obj |jq -r '.secondaryMetrics.transactionNodeCount.score')
            TAGS=$(jo -a "branch:$CIRCLE_BRANCH" "hash:$HASH" "workflow:$CIRCLE_WORKFLOW_ID" "job:$CIRCLE_JOB" "build:$CIRCLE_BUILD_NUM" "url:$CIRCLE_BUILD_URL" "container:$CIRCLE_NODE_INDEX" "snapshotVersion:$SNAPSHOT_VERSION" "choiceName:$CHOICE_NAME" "contractIdVersion:$CONTRACT_ID_VERSION" "gasOn:$GAS_ON")

            ./scripts/ci/post-to-datadog.sh "$TIMESTAMP" rate "$TAGS" "transaction.snapshot.benchmark=$BENCHMARK"
            ./scripts/ci/post-to-datadog.sh "$TIMESTAMP" count "$TAGS" "transaction.snapshot.stepCount=$STEP_COUNT" "transaction.snapshot.fetchNodeCount=$FETCH_NODE_COUNT" "transaction.snapshot.nodeCount=$TRANSACTION_NODE_COUNT"
          done
