include required("performance/shared.conf")
include required("performance/postgres/persistence.conf")
include required("performance/topology/baseparticipant.conf")

canton {
  participants {
    opspar = ${_baseparticipant}
    opspar {
      ledger-api.port = 10008
      admin-api.port = 10009
      storage.config.properties {
        databaseName = "opspar"
        currentSchema = "opspar"
      }
    }
  }
}
