-- Traffic enforcement tables

-- Drop the event table to re-create it from scratch.
-- That's ok because the events were never exposed nor advertised as a supported feature in this release.
-- The balance per account is kept which maintains traffic balance continuity.
drop table par_traffic_enforcement_event;

-- Changes compared to the initial version:
-- - event_type has been repurposed to indicate how to apply the event to the account balance (e.g DELTA_DEBIT, DELTA_CREDIT)
create table par_traffic_enforcement_event
(
    -- Increasing sequence number for each event
    -- This is used to provide a total ordering of events
    sequence_nb  bigint generated always as identity,
    -- Event source is a small integer that identifies the source of the event (e.g: 0 == LEDGER_API_COMPLETIONS, 1 = TEA_API)
    event_source smallint not null,
    -- Event type identifies how to apply the event to the account balance (e.g CREDIT_DELTA, DEBIT_DELTA)
    event_type   smallint not null,
    -- Event ID is a unique identifier per event_source, it is used for event deduplication
    event_id     varchar  not null,
    -- Account ID is the identifier of the account that the event applies to
    account_id   varchar  not null,
    -- Amount is the amount of traffic tied to the event, it can be positive or negative.
    -- The actual semantics depend on the event_type.
    amount       bigint   not null,
    -- Timestamp when the event was recorded
    -- Critically this is NOT the record time of a transaction. It is generated by the database.
    -- Note that it is possible for events to have timestamps reversed compared to their sequence number
    timestamp    bigint   not null,
    -- Events are unique per (event_source, event_id).
    primary key (event_source, event_id)
);

-- Now update the par_traffic_enforcement_balance table to remove the event_type column,
-- which is no longer needed there as it now has a different meaning in the event table.

-- 1. Drops PK
ALTER TABLE par_traffic_enforcement_balance
    DROP PRIMARY KEY;

-- 2. Drop the column
ALTER TABLE par_traffic_enforcement_balance
    DROP COLUMN event_type;

-- 3. Re-add primary key
ALTER TABLE par_traffic_enforcement_balance
    ADD PRIMARY KEY (account_id);
