// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package com.digitalasset.canton.ledger.participant.state

import com.digitalasset.canton.config.RequireTypes.{NonNegativeInt, NonNegativeLong}
import com.digitalasset.canton.data.CantonTimestamp
import com.digitalasset.canton.logging.pretty.{Pretty, PrettyPrinting, PrettyUtil}
import com.digitalasset.canton.util.ShowUtil
import com.google.common.annotations.VisibleForTesting

/** Indexing watermark relative to a canton participant staging area for feeding the indexer events
  * with contract activation changes in a causality preserving order. This class is used to track
  * indexer progress for crash recovery.
  *
  * @param timestamp
  *   the timestamp of the last indexed contract activation change
  * @param counter
  *   a lexicographically nested counter relative to timestamp
  * @param acsCommitmentTiebreaker
  *   tiebreaker for AcsCommitmentProcessor, incremented each time a watermark is generated by
  *   deferred OnPR indexing
  */
final case class IndexingWatermark(
    timestamp: CantonTimestamp,
    counter: NonNegativeLong,
    acsCommitmentTiebreaker: NonNegativeInt,
) extends PrettyPrinting {

  override protected def pretty: Pretty[IndexingWatermark] =
    prettyOfClass(
      param("timestamp", _.timestamp),
      param("counter", _.counter),
      param("tiebreaker", _.acsCommitmentTiebreaker),
    )
}

object IndexingWatermark extends PrettyUtil with ShowUtil {
  implicit val orderingIndexingWatermark: Ordering[IndexingWatermark] =
    Ordering.by[IndexingWatermark, (CantonTimestamp, NonNegativeLong, NonNegativeInt)](watermark =>
      (watermark.timestamp, watermark.counter, watermark.acsCommitmentTiebreaker)
    )

  @VisibleForTesting
  def fromTimestamp(ts: CantonTimestamp): IndexingWatermark =
    IndexingWatermark(ts, NonNegativeLong.zero, NonNegativeInt.zero)
}
