canton {
  # Exporting keys require preview flag
  features.enable-preview-commands = yes

  # support the alpha protocol version
  parameters.non-standard-config = yes
  parameters.alpha-version-support = yes

  sequencers {
    sequencer1 {
      storage.type = memory
      public-api.port = 5001
      admin-api.port = 5002

      parameters.alpha-version-support = yes
    }

    sequencer2 {
      storage.type = memory
      public-api.port = 5011
      admin-api.port = 5012

      # LSU specific parameters
      init.identity.type = manual
      init.generate-topology-transactions-and-keys = false

      parameters.alpha-version-support = yes
    }
  }

  mediators {
    mediator1 {
      storage.type = memory
      admin-api.port = 5202

      parameters.alpha-version-support = yes
    }
    mediator2 {
      storage.type = memory
      admin-api.port = 5212

      # LSU specific parameters
      init.identity.type = manual
      init.generate-topology-transactions-and-keys = false

      parameters.alpha-version-support = yes
    }
  }

  participants {
    participant1 {
      storage.type = memory
      admin-api.port = 5112
      ledger-api.port = 5111
      http-ledger-api.port = 5013

      parameters.alpha-version-support = yes
    }
    participant2 {
      storage.type = memory
      admin-api.port = 5022
      ledger-api.port = 5021
      http-ledger-api.port = 5023

      parameters.alpha-version-support = yes
    }
  }
}
