include required("performance/shared.conf")
include required("performance/postgres/persistence.conf")
include required("performance/topology/baseparticipant.conf")

canton {
  participants {
    participant1 = ${_baseparticipant}
    participant1 {
      ledger-api.port = 10011
      admin-api.address = "0.0.0.0"
      admin-api.port = 10012
      storage.config.properties {
        databaseName = "participant1"
        currentSchema = "participant1"
      }
    }
    participant2 = ${_baseparticipant}
    participant2 {
      ledger-api.port = 10021
      admin-api.address = "0.0.0.0"
      admin-api.port = 10022
      storage.config.properties {
        databaseName = "participant2"
        currentSchema = "participant2"
      }
    }
    participant3 = ${_baseparticipant}
    participant3 {
      ledger-api.port = 10031
      admin-api.address = "0.0.0.0"
      admin-api.port = 10032
      storage.config.properties {
        databaseName = "participant3"
        currentSchema = "participant3"
      }
    }
  }
}
