when:
  and:
   - not: << pipeline.parameters.test_to_run_many_times >>
   - equal: [ "none", << pipeline.parameters.manual_job >>]
max_auto_reruns: 1

jobs:
##### The required jobs to build canton
  - compile:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
      filters:
        tags:
          only: /^v.*/
        branches:
          ignore:
            - /^gha-migration\/.*/ # Do not run the CCI job on the GHA migration branches
  - package_community:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
      is_nightly_workflow: false
      is_manual: false
      filters:
        tags:
          only: /^v.*/
        branches:
          ignore:
            - /^gh-readonly-queue\/main\/.*/ # Do not run check on GH merge queue branches to speed up merge queue jobs
      requires:
        - compile # optional dependency, introduced to save credits in case of compile errors

##### Static analysis
  - verify_circleci_config_and_compliance_label:
      filters:
        branches:
          ignore:
            - main
            - /^release-line.*/
            - /^gh-readonly-queue\/main\/.*/ # Do not run check on GH merge queue branches as they don't have a PR associated
        tags:
          only: /^v.*/
  - static_tests:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
      filters:
        branches:
          ignore:
            - /^gha-migration\/.*/ # Do not run the CCI job on the GHA migration branches
  - protobuf_continuity:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
      requires:
        - compile
      filters:
        branches:
          ignore:
            - /^gh-readonly-queue\/main\/.*/ # Do not run check on GH merge queue branches to speed up merge queue jobs

##### Build documentation
  - build_scaladoc:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
      filters:
        tags:
          only: /^v.*/
        branches:
          ignore:
            - /^gh-readonly-queue\/main\/.*/ # Do not run check on GH merge queue branches to speed up merge queue jobs
      requires:
        - compile # optional dependency, introduced to save credits in case of compile errors
  - build_docs:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
      filters:
        branches:
          ignore:
            - /^gh-readonly-queue\/main\/.*/ # Do not run check on GH merge queue branches to speed up merge queue jobs
        tags:
          only: /^v.*/
      requires:
        - package_community
        - build_scaladoc

##### Tests
  - test:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
        - aws_kms_testing
        - gcp_kms_testing
      filters:
        tags:
          only: /^v.*/
        branches:
          ignore:
            - /^gh-readonly-queue\/main\/.*/ # Do not run check on GH merge queue branches to speed up merge queue jobs, we run the smoke_test instead
      requires:
        - compile # optional dependency, introduced to save credits in case of compile errors
  - smoke_test:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
        - aws_kms_testing
        - gcp_kms_testing
      filters:
        branches:
          only:
            - /^gh-readonly-queue\/main\/.*/ # Only run a smoke test on GH merge queue branches to speed up merge queue jobs
      requires:
        - compile # optional dependency, introduced to save credits in case of compile errors
  - test:
      name: test_protocol_version_34
      protocol_version: "34"
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
        - aws_kms_testing
        - gcp_kms_testing
      requires:
        - compile
      filters:
        branches:
          ignore:
            - /^gh-readonly-queue\/main\/.*/ # Do not run check on GH merge queue branches to speed up merge queue jobs
  - test:
      name: test_protocol_version_dev
      protocol_version: "DEV"
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
        - aws_kms_testing
        - gcp_kms_testing
      filters:
        branches:
          only:
            - main
            - /^release-line.*/
        tags:
          only: /^v.*/
      requires:
        - test_protocol_version_34
  - unstable_test:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
        - aws_kms_testing
        - gcp_kms_testing
      filters:
        branches:
          only:
            - main
            - /^release-line.*/
        tags:
          only: /^v.*/
      requires:
        - package_community # optional dependency, introduced to save credits in case of compile errors
  - variations_test:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
        - aws_kms_testing
        - gcp_kms_testing
      filters:
        branches:
          only:
            - main
            - /^release-line.*/
        tags:
          only: /^v.*/
      requires:
        - compile # optional dependency, introduced to save credits in case of compile errors
  - variations_test: # this variations_test is the complement of the above: running for selected users on feature branches
      only_for_selected_users: true
      name: variation_test_selected_users_only
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
        - aws_kms_testing
        - gcp_kms_testing
      filters:
        branches:
          ignore:
            - main
            - /^release-line.*/
            - /^gh-readonly-queue\/main\/.*/ # Do not run check on GH merge queue branches to speed up merge queue jobs
      requires:
        - compile
  - ledger_api_compatibility_tests:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
      filters:
        branches:
          only:
            - main
            - /^release-line.*/
        tags:
          only: /^v.*/
      requires:
        - compile # optional dependency, introduced to save credits in case of compile errors
  - protocol_continuity_test_latest:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - da-images
        - maven-mirror
        - aws_kms_testing
        - gcp_kms_testing
      filters:
        branches:
          ignore:
            - /^gh-readonly-queue\/main\/.*/ # Do not run check on GH merge queue branches to speed up merge queue jobs
        tags:
          only: /^v.*/
      requires:
        - compile # optional dependency, introduced to save credits in case of compile errors
  - scalafix:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
      filters:
        tags:
          only: /^v.*/
      requires:
        - compile
  - sequential_test:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
        - aws_kms_testing
        - gcp_kms_testing
      filters:
        tags:
          only: /^v.*/
        branches:
          only:
            - main
            - /^release-line.*/
      requires:
        - compile # optional dependency, introduced to save credits in case of compile errors
        - test # depend on test job to execute the big test jobs sequentially
  - crash_recovery_test:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
        - aws_kms_testing
        - gcp_kms_testing
      filters:
        branches:
          ignore:
            - /^gh-readonly-queue\/main\/.*/ # Do not run check on GH merge queue branches to speed up merge queue jobs
        tags:
          only: /^v.*/
      requires:
        - compile # optional dependency, introduced to save credits in case of compile errors
  - toxiproxy_test_fast:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
        - aws_kms_testing
        - gcp_kms_testing
      filters:
        branches:
          ignore:
            - /^gh-readonly-queue\/main\/.*/ # Do not run check on GH merge queue branches to speed up merge queue jobs
        tags:
          only: /^v.*/
      requires:
        - compile # optional dependency, introduced to save credits in case of compile errors

### for release-lines we want to run data continuity tests as part of the continuous integration
  - test_data_continuity_dumps:
      context:
        - datadog
        - artifactory
        - azure-self-cache
        - maven-mirror
        - da-images
      requires:
        - compile
      filters:
        branches:
          ignore:
            - /^gh-readonly-queue\/main\/.*/ # Do not run check on GH merge queue branches to speed up merge queue jobs

