_baseparticipant = {
  parameters {
    alpha-version-support = yes
    beta-version-support = yes
    do-not-await-on-checking-incoming-commitments = yes
    ledger-api-server.indexer.postgres-data-source.client-connection-check-interval = 0ms
    caching {
      contract-store = {
        maximum-size = 100000
        expire-after-access = 120s
      }
    }
    reassignments-config.target-timestamp-forward-tolerance = 60s
  }
  topology {
    dispatch-queue-backpressure-limit = 10000
    broadcast-batch-size = 1000
  }
  storage = ${_shared.storage}
  storage.parameters.connection-allocation {
    num-reads = 8
    num-writes = 8
    num-ledger-api = 8
  }
  ledger-api {
    tls = ${?_shared.ledger-api-tls}
    postgres-data-source.synchronous-commit = off
    // postgres-data-source.client-connection-check-interval = 0ms
    index-service {
      max-contract-state-cache-size = 250000      // default 1e4
      max-contract-key-state-cache-size = 100000  // default 1e4
    }
  }
  http-ledger-api.enabled = false
  init.ledger-api.max-deduplication-duration = 30m
}
