include required("baseparticipant.conf")
canton {
  participants {
    participant1 = ${_baseparticipant}
    participant1 {
      storage.config.properties.databaseName = ${?DBPREFIX}participant1
      ledger-api.port = 10011
      admin-api.port = 10012
    }
    participant2 = ${_baseparticipant}
    participant2 {
      storage.config.properties.databaseName = ${?DBPREFIX}participant2
      ledger-api.port = 10021
      admin-api.port = 10022
    }
//     participant3 = ${_baseparticipant}
//     participant3 {
//       storage.config.properties.databaseName = ${?DBPREFIX}participant3
//       ledger-api.port = 10031
//       admin-api.port = 10032
//     }
//     participant4 = ${_baseparticipant}
//     participant4 {
//       storage.config.properties.databaseName = ${?DBPREFIX}participant4
//       ledger-api.port = 10041
//       admin-api.port = 10042
//     }
//     participant5 = ${_baseparticipant}
//     participant5 {
//       storage.config.properties.databaseName = ${?DBPREFIX}participant5
//       ledger-api.port = 10051
//       admin-api.port = 10052
//     }
//     participant6 = ${_baseparticipant}
//     participant6 {
//       storage.config.properties.databaseName = ${?DBPREFIX}participant6
//       ledger-api.port = 10061
//       admin-api.port = 10062
//     }
  }
}
