include required("basesequencer.conf")
canton {
    sequencers {
        sequencer1 = ${_basesequencer}
        sequencer1 {
            public-api.port = 4401
            admin-api.port = 4402
            storage.config.properties.databaseName = ${?DBPREFIX}sequencer1
        }
//         sequencer2 = ${_basesequencer}
//         sequencer2 {
//             public-api.port = 4411
//             admin-api.port = 4412
//             storage.config.properties.databaseName = ${?DBPREFIX}sequencer2
//         }
//         sequencer3 = ${_basesequencer}
//         sequencer3 {
//             public-api.port = 4421
//             admin-api.port = 4422
//             storage.config.properties.databaseName = ${?DBPREFIX}sequencer3
//         }
//         sequencer4 = ${_basesequencer}
//         sequencer4 {
//             public-api.port = 4431
//             admin-api.port = 4432
//             storage.config.properties.databaseName = ${?DBPREFIX}sequencer4
//         }
    }
}
