include required("sequencers.conf")
include required("basesequencer-reference.conf")
canton {
    sequencers {
        sequencer1.sequencer = ${_sequencer}
        //sequencer2.sequencer = ${_sequencer}
        //sequencer3.sequencer = ${_sequencer}
        //sequencer4.sequencer = ${_sequencer}
    }
}
