include required("../shared.conf")
include required("baseparticipant.conf")
host="localhost"
host=${?PUBLIC_ADDRESS}
canton {
  participants {
    participant1 = ${_baseparticipant}
    participant1 {
      storage.config.properties.databaseName = ${?DBPREFIX}participant1
      ledger-api {
        port = 10011
        address=${host}
      }
      admin-api {
        port = 10012
        address=${host}
      }
    }
    participant2 = ${_baseparticipant}
    participant2 {
      storage.config.properties.databaseName = ${?DBPREFIX}participant2
      ledger-api {
        port = 10021
        address=${host}
      }
      admin-api {
        port = 10022
        address=${host}
      }
    }
  }
}
