include required("xfer-synchronizer.conf")
include required("xfer-participants.conf")
canton {
  participants {
    opsparticipant = ${_baseparticipant}
    opsparticipant {
      storage.config.properties.databaseName = ${?DBPREFIX}opsparticipant
      ledger-api.port = 10008
      admin-api.port = 10009
    }
  }
}
