include required("../shared.conf")
include required("basemediator.conf")
include required("basesequencer.conf")
include required("basesequencer-reference.conf")
canton {
  sequencers {
    sequencer = ${_basesequencer}
    sequencer.sequencer = ${_sequencer}
    sequencer {
      public-api.port = 10002
      admin-api.port = 10003
      storage.config.properties.databaseName = ${?DBPREFIX}sequencer
    }
  }
  mediators {
    mediator = ${_basemediator}
    mediator {
        storage.config.properties.databaseName = ${?DBPREFIX}mediator
        admin-api.port = 10001
    }
  }
}
