// Copyright (c) 2026 Digital Asset (Switzerland) GmbH and/or its affiliates. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

package com.digitalasset.canton.participant.config

import com.digitalasset.daml.lf.engine.EngineLoggingConfig
import com.digitalasset.daml.lf.transaction.NextGenContractStateMachine as ContractStateMachine

import java.nio.file.Path

/** Configure the behaviour of the Daml Engine
  *
  * @param enableEngineStackTraces
  *   If true, DAMLe stack traces will be enabled
  * @param iterationsBetweenInterruptions
  *   Number of engine iterations between forced interruptions (outside needs of information).
  * @param submissionPhaseLogging
  *   Configuration for logging in phase one (command submission) of canton transaction processing
  * @param validationPhaseLogging
  *   Configuration for logging in phase three (transaction validation) of canton transaction
  *   processing
  * @param enableAdditionalConsistencyChecks
  *   When true, extra consistency checks are performed for transactions, ensuring that
  *   serialization/deserialization and enrichment/impoverishment processes remain idempotent on
  *   transaction outputs generated by the engine. Requires canton.parameters.non-standard-config =
  *   true
  * @param contractStateMode
  *   Contract state machine is configured to use this mode for validating transactions. To modify
  *   the default value requires canton.parameters.non-standard-config = true
  * @param profileDir
  *   path to the directory used for Daml profiling
  * @param snapshotDir
  *   path to the directory used for saving transaction tree snapshots
  * @param extensions
  *   Configuration for external extension services that can be called from Daml contracts.
  *   Map from extension ID to extension service configuration.
  * @param extensionSettings
  *   Global settings for engine extensions
  */
final case class CantonEngineConfig(
    enableEngineStackTraces: Boolean = false,
    iterationsBetweenInterruptions: Long =
      10000, // 10000 is the default value in the engine configuration
    submissionPhaseLogging: EngineLoggingConfig = EngineLoggingConfig(enabled = true),
    validationPhaseLogging: EngineLoggingConfig = EngineLoggingConfig(enabled = false),
    enableAdditionalConsistencyChecks: Boolean = false,
    contractStateMode: ContractStateMachine.Mode = ContractStateMachine.Mode.default,
    profileDir: Option[Path] = None,
    snapshotDir: Option[Path] = None,
    extensions: Map[String, ExtensionServiceConfig] = Map.empty,
    extensionSettings: EngineExtensionsConfig = EngineExtensionsConfig.default,
)
