{
 "title": "BFT ordering (performance)",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "Namespace",
    "query": {
     "query": "label_values(daml_health_status,namespace)"
    }
   },
   {
    "name": "job",
    "label": "Job",
    "query": {
     "query": "label_values(daml_health_status{namespace=~\"$namespace\"},job)"
    }
   },
   {
    "name": "node",
    "label": "Node",
    "query": {
     "query": "label_values(daml_health_status{namespace=~\"$namespace\", job=~\"$job\"},node)"
    }
   },
   {
    "name": "percentile",
    "label": "Percentile",
    "query": ".5,.6,.7,.75,.8,.9,.95,.99,.999"
   }
  ]
 },
 "panels": [
  { "title": "Global", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Requests end-to-end ordering latency",
   "type": "timeseries",
   "description": "Wall-clock duration between the instant a request is received by the CantonBFT orderer and the instant the fully assembled ordered block metadata is stored, just before the request is pushed to the post-ordering stages. Its meaningfulness requires wall-clock synchronization, as not all ordered requests are received and timestamped on this node.",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_global_requests_ordering_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Total batch dissemination and consensus time (permanence in availability module)",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile($percentile, sum by (namespace, job, node, ordering_stage) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"batch-availability-total\"}[$__rate_interval])))",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Throughput - blocks/s",
   "type": "timeseries",
   "description": "Rate of blocks ordered and output to the read path.",
   "gridPos": { "h": 17, "w": 8, "x": 0, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, node, is_block_empty) (irate(daml_sequencer_bftordering_global_ordered_blocks_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}.{{node}} (empty: {{is_block_empty}})"
    }
   ]
  },
  {
   "title": "Throughput - batches/s",
   "type": "timeseries",
   "description": "Rate of batches (proofs of availability) ordered and output to the read path.",
   "gridPos": { "h": 17, "w": 8, "x": 8, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "irate(daml_sequencer_bftordering_global_ordered_batches_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Throughput - requests/s",
   "type": "timeseries",
   "gridPos": { "h": 17, "w": 8, "x": 16, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "cps" } },
   "targets": [
    {
     "expr": "sum by (namespace, job, node) (irate(daml_sequencer_bftordering_global_ordered_requests_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval]))",
     "legendFormat": "{{namespace}}.{{node}}"
    }
   ]
  },
  {
   "title": "Networking",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "PekkoP2PGrpcConnectionManagingActor queue latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 31 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by(namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"module-queue-PekkoP2PGrpcConnectionManagingActor\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "PekkoP2PGrpcConnectionManagingActor queue size",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 31 },
     "targets": [
      {
       "expr": "sum by (namespace, job, node) (daml_sequencer_bftordering_performance_moduleQueueSize_PekkoP2PGrpcConnectionManagingActor{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"})",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "P2P gRPC network latency",
     "type": "timeseries",
     "description": "Latency between sending a message and receiving it on the other side",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node, source_sequencer) (rate(daml_sequencer_bftordering_p2p_send_grpc_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "(reporter: {{namespace}}.{{node}}) {{source_sequencer}}"
      }
     ]
    },
    {
     "title": "gRPC send retry rate",
     "type": "timeseries",
     "description": "The rate of gRPC message send retries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (namespace, job, node, target_sequencer) (irate(daml_sequencer_bftordering_p2p_send_sends_retried{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval]))",
       "legendFormat": "{{namespace}}.{{node}}.{{target_sequencer}}"
      }
     ]
    },
    {
     "title": "P2P network client write latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_p2p_send_network_write_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "P2P receive processing latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by(namespace, job, node) (rate(daml_sequencer_bftordering_p2p_receive_processing_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Mempool+Availability",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 31 },
   "collapsed": true,
   "panels": [
    {
     "title": "Mempool module queue latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 32 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"module-queue-mempool\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Mempool module queue size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 32 },
     "targets": [
      {
       "expr": "daml_sequencer_bftordering_performance_moduleQueueSize_mempool{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Availability module queue latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"module-queue-availability\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Availability module queue size",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 38 },
     "targets": [
      {
       "expr": "daml_sequencer_bftordering_performance_moduleQueueSize_availability{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Time spent waiting for batches",
     "type": "timeseries",
     "description": "Time waited for a batch while there are outstanding consensus proposal requests and no dissemination is in progress",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"batch-wait\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Total dissemination time",
     "type": "timeseries",
     "description": "Cumulative latency of a batch dissemination until a PoA is formed and it can be present multiple times for a given batch if it regresses due to topology changes",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"batch-dissemination-total\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Time waited for batch inclusion in consensus proposal",
     "type": "timeseries",
     "description": "Insertion in proposal queue until next event, like re-sign, re-dissemination, [re-]proposal or batch ordered (emitted 1 or more times per batch)",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"batch-queued-for-block-inclusion\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Batch dissemination regressions rate",
     "type": "timeseries",
     "description": "Rate of regressions of a single batch due to topology changes",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 50 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(daml_sequencer_bftordering_availability_batch_regressions{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{namespace}}.{{node}}, {{stage}}"
      }
     ]
    },
    {
     "title": "Batch ID hashing latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"availability-hash-batchId\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Local Batch ID signing latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 56 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"availability-sign-local-batchId\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Request batch inclusion latency",
     "type": "timeseries",
     "description": "Insertion in batch queue until extraction and batch send to availability",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"request-queued-for-batch-inclusion\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Remote batch ID signing latency",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"availability-sign-remote-batchId\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Sign local batches",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"availability-sign-local-batches\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Batch ID signature verification",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 68 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"availability-signature-verify-ack\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Insert batch",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.availability.data.db.DbAvailabilityStore.addBatch\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Fetch local batches from DB",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 74 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.availability.data.db.DbAvailabilityStore.fetchBatches\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Batch validation",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"batch-validation\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Availability Store Cache Statistics",
     "type": "timeseries",
     "description": "Summary of cache hits, misses, and evictions for the Availability store's batch data cache",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "sum by (namespace, job, node) (irate(daml_cache_hits{namespace=~\"$namespace\", job=~\"$job\", node=~\"$node\", cache=\"batch-cache\"}[$__rate_interval]))",
       "legendFormat": "{{namespace}}.{{node}} Cache Hits"
      },
      {
       "expr": "sum by (namespace, job, node) (irate(daml_cache_misses{namespace=~\"$namespace\", job=~\"$job\", node=~\"$node\", cache=\"batch-cache\"}[$__rate_interval]))",
       "legendFormat": "{{namespace}}.{{node}} Cache Misses"
      },
      {
       "expr": "sum by (namespace, job, node) (irate(daml_cache_evictions{namespace=~\"$namespace\", job=~\"$job\", node=~\"$node\", cache=\"batch-cache\"}[$__rate_interval]))",
       "legendFormat": "{{namespace}}.{{node}} Cache Evictions"
      }
     ]
    },
    {
     "title": "Number of batches that need to be fetched",
     "type": "timeseries",
     "description": "Batches that have been ordered, but aren't available locally so need to be fetched from other peers.",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 86 },
     "targets": [
      {
       "expr": "sum by (namespace, job, node, Leader) (irate(daml_sequencer_bftordering_availability_missing_batches_need_output_fetch_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[1m]))",
       "legendFormat": "(reporter {{namespace}}.{{node}}): originator {{Leader}}"
      }
     ]
    },
    {
     "title": "Output Fetch Latency",
     "type": "timeseries",
     "description": "The time from first output fetch request until we get a response.",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node,From) (rate(daml_sequencer_bftordering_availability_output_fetch_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "(reporter {{namespace}}.{{node}}) from {{From}}"
      }
     ]
    },
    {
     "title": "Output Fetch Timeouts",
     "type": "timeseries",
     "description": "The rate of batch fetch timeouts per fetch request recipient",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 94 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "increase(daml_sequencer_bftordering_availability_output_fetch_timeouts{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[1m])",
       "legendFormat": "(reporter {{namespace}}.{{node}}) from {{From}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus - main protocol",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 32 },
   "collapsed": true,
   "panels": [
    {
     "title": "Consensus module queue latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"module-queue-consensus\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Consensus module queue size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
     "targets": [
      {
       "expr": "daml_sequencer_bftordering_performance_moduleQueueSize_consensus{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Segment module queue latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"module-queue-segment-module\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Segment module queue size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "targets": [
      {
       "expr": "daml_sequencer_bftordering_performance_moduleQueueSize_segment_module{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Consensus Block Latency",
     "type": "timeseries",
     "description": "Block commit time at the consensus (PBFT) level.",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_consensus_commit_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Consensus segment block proposal to commit latency",
     "type": "timeseries",
     "description": "Time elapsed between sending a PrePrepare and seeing that the block has been ordered",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"consensus-segment-proposal-to-commit-latency\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Consensus segment block ordering latency",
     "type": "timeseries",
     "description": "Time elapsed between ordered blocks proposed by a segment",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"consensus-segment-block-commit-latency\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Wait for proposal",
     "type": "timeseries",
     "description": "Time between a proposal request to the availability module needed to continue a segment and a PrePrepare being built",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"consensus-block-proposal-wait\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Wait for epoch start",
     "type": "timeseries",
     "description": "Time between the epoch completion and the start of the next epoch",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"consensus-epoch-start-wait\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Wait for epoch completion",
     "type": "timeseries",
     "description": "Time between the last led segment's completion and the epoch completion",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 60 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"consensus-epoch-completion-wait\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Start epoch (DB)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.consensus.iss.data.db.DbEpochStore.startEpoch\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Complete epoch (DB)",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 67 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.consensus.iss.data.db.DbEpochStore.completeEpoch\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Insert pre-prepare",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.consensus.iss.data.db.DbEpochStore.addPrePrepare\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Insert prepares",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.consensus.iss.data.db.DbEpochStore.addPreparesAtomically\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Insert ordered block",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.consensus.iss.data.db.DbEpochStore.addOrderedBlockAtomically\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Check PoA ack signature",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"consensus-signature-verify-poa-ack\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Validate message",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"consensus-validate-signed-message\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Sign message",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 86 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"sign-BftSignedConsensusMessage\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Relative peer segment completion delay",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by(namespace, job, node, Leader) (rate(daml_sequencer_bftordering_consensus_relative_segment_latency_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", node=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "(reporter: {{namespace}}.{{node}}) {{Leader}}"
      }
     ]
    },
    {
     "title": "Segment Flush Block Rate",
     "type": "timeseries",
     "description": "Rate of empty blocks created due to segment flushing, in which a node detects that a strong quorum of peers have already finished their segment, and thus the local segment should be rushed (flushed) to completion to reduce ordering and delivery delays.",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 92 },
     "fieldConfig": { "defaults": { "unit": "cps" } },
     "targets": [
      {
       "expr": "irate(daml_sequencer_bftordering_consensus_flushed_blocks_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus - view change",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 33 },
   "collapsed": true,
   "panels": [
    {
     "title": "View changes occurred (rate)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "none" } },
     "targets": [
      {
       "expr": "irate(daml_sequencer_bftordering_consensus_epoch_view_changes{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Insert view change message",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.consensus.iss.data.db.DbEpochStore.addViewChangeMessage\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Postponed view messages queue latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 41 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"consensus-postponed-view-messages-queue-latency\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Postponed view messages queue size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 48 },
     "targets": [
      {
       "expr": "irate(daml_sequencer_bftordering_consensus_postponed_view_messages_queue_size{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Postponed view messages queue max size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 48 },
     "targets": [
      {
       "expr": "daml_sequencer_bftordering_consensus_postponed_view_messages_queue_max_size{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Postponed view messages dropped (rate)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
     "targets": [
      {
       "expr": "irate(daml_sequencer_bftordering_consensus_postponed_view_messages_dropped_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Postponed view messages duplicated (rate)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
     "targets": [
      {
       "expr": "irate(daml_sequencer_bftordering_consensus_postponed_view_messages_duplicates_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Time until progress in view",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 62 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by(namespace, job, node, Leader) (rate(daml_sequencer_bftordering_consensus_view_change_progress_latency_duration_seconds{namespace=~\"$namespace\", job=~\"$job\", node=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "(reporter: {{namespace}}.{{node}}) {{Leader}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus - state transfer",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 34 },
   "collapsed": true,
   "panels": [
    {
     "title": "Validate state transfer consensus certificate",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"consensus-validate-consensus-certificate\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Epoch Transfer Duration",
     "type": "timeseries",
     "description": "Time to transfer a given epoch from peer(s)",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 80 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\", ordering_stage=~\"state-transfer-total-epoch-transfer-latency\"}[$__rate_interval])))",
       "legendFormat": "Data transfer"
      },
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\", ordering_stage=~\"state-transfer-store-epochs\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Postponed consensus messages queue latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 42 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"state-transfer-postponed-consensus-messages-queue-latency\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Postponed consensus messages queue size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "daml_sequencer_bftordering_consensus_state_transfer_postponed_consensus_messages_queue_size{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Postponed consensus messages queue max size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 49 },
     "targets": [
      {
       "expr": "daml_sequencer_bftordering_consensus_state_transfer_postponed_consensus_messages_queue_max_size{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Postponed consensus messages dropped (rate)",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 49 },
     "targets": [
      {
       "expr": "irate(daml_sequencer_bftordering_consensus_state_transfer_postponed_consensus_messages_dropped{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus - retransmissions",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 35 },
   "collapsed": true,
   "panels": [
    {
     "title": "Incoming retransmission requests rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 36 },
     "targets": [
      {
       "expr": "irate(daml_sequencer_bftordering_consensus_incoming_retransmission_requests_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Outgoing retransmission requests rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 36 },
     "targets": [
      {
       "expr": "irate(daml_sequencer_bftordering_consensus_outgoing_retransmission_requests_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Retransmitted messages rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 42 },
     "targets": [
      {
       "expr": "irate(daml_sequencer_bftordering_consensus_retransmitted_messages_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Retransmitted commit certificates rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 42 },
     "targets": [
      {
       "expr": "irate(daml_sequencer_bftordering_consensus_retransmitted_commit_certificates_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Sign retransmission message",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"sign-BftSignedRetransmissionMessage\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Verify retransmission message signature",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 48 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"verify-signature-BftSignedRetransmissionMessage\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Retransmission responses discarded due to wrong epoch - rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 0, "y": 54 },
     "targets": [
      {
       "expr": "irate(daml_sequencer_bftordering_consensus_discarded_wrong_epoch_retransmission_responses_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Retransmission requests discarded due to rate limiting - rate",
     "type": "timeseries",
     "gridPos": { "h": 6, "w": 12, "x": 12, "y": 54 },
     "targets": [
      {
       "expr": "irate(daml_sequencer_bftordering_consensus_discarded_rate_limited_retransmission_requests_total{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Consensus - CFT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 36 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load latest epoch",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.consensus.iss.data.db.DbEpochStore.latestEpoch\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Load epoch progress",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.consensus.iss.data.db.DbEpochStore.loadEpochProgress\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Load completed blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.consensus.iss.data.db.DbEpochStore.loadCompleteBlocks\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Output",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 37 },
   "collapsed": true,
   "panels": [
    {
     "title": "Output stage duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"output-stage-duration\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Output module queue latency",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 45 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"module-queue-output\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Output module queue size",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 45 },
     "targets": [
      {
       "expr": "daml_sequencer_bftordering_performance_moduleQueueSize_output{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Block inspection",
     "type": "timeseries",
     "description": "Time needed to inspect requests within a block",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"output-block-inspection\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Total block batches fetch time",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"output-block-fetch-batches\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Insert block",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.output.data.db.DbOutputMetadataStore.insertBlockIfMissing\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Query topology",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 59 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_topology_query_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Save blacklist leader selection policy state",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.output.data.db.DbOutputMetadataStore.insertLeaderSelectionPolicyState\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Insert epoch metadata",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 66 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.output.data.db.DbOutputMetadataStore.insertEpochIfMissing\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Sequencer core backpressure duration",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 73 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"output-backpressure\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Output - CFT",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 38 },
   "collapsed": true,
   "panels": [
    {
     "title": "Load epoch info",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 39 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.consensus.iss.data.db.DbEpochStore.loadEpochInfo\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Load ordered blocks",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.consensus.iss.data.db.DbEpochStore.loadOrderedBlocks\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Pruning",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 39 },
   "collapsed": true,
   "panels": [
    {
     "title": "Compute pruning point",
     "type": "timeseries",
     "description": "Time to compute the pruning point, based on retention factors and current time",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"pruning-compute-pruning-point\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Availability DB - evict expired batches",
     "type": "timeseries",
     "description": "Time to evict unordered, but expired, batches in the availability DB",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.availability.data.db.DbAvailabilityStore.gc\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Create partitions",
     "type": "timeseries",
     "description": "Time to create new table partitions, when necessary",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.pruning.PartitionManager.PartitionCreatorImpl.createPartitionsIfNeeded\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Prune (Delete partitions)",
     "type": "timeseries",
     "description": "Time to drop table partitions that can be pruned",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.pruning.PartitionManager.PartitionPrunerImpl.prune\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    },
    {
     "title": "Partition manager startup",
     "type": "timeseries",
     "description": "Time to start the Partition Manager, which may include creating new partitions",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "histogram_quantile($percentile, sum by (namespace, job, node) (rate(daml_sequencer_bftordering_performance_ordering_stage_latency_duration_seconds{namespace=~\"$namespace\",job=~\"$job\",node=~\"$node\",ordering_stage=~\"com.digitalasset.canton.synchronizer.sequencer.block.bftordering.core.modules.pruning.PartitionManager.create\"}[$__rate_interval])))",
       "legendFormat": "{{namespace}}.{{node}}"
      }
     ]
    }
   ]
  }
 ]
}