name: Package Community
on:
  workflow_call:
    inputs:
      is_nightly_workflow:
        description: Whether this is a nightly workflow run
        required: false
        type: boolean
        default: false
      is_manual:
        description: Whether this is a manual workflow run
        required: false
        type: boolean
        default: false
    secrets:
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true

jobs:
  package-community:
    name: Package Community
    runs-on: dach-ny-canton
    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      EXECUTOR_JVM_HEAP_SIZE: 4500M
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with: {fetch-depth: 0}

      - name: Obtain Release Suffix
        id: release_suffix
        uses: ./.github/actions/build/obtain_release_suffix
        with:
          is_nightly_workflow: ${{ inputs.is_nightly_workflow }}
          is_manual: ${{ inputs.is_manual }}

      - name: Package community-app
        uses: ./.github/actions/canton/package
        env:
          RELEASE_SUFFIX: ${{ steps.release_suffix.outputs.release_suffix }}
        with:
          cmd: community-app/bundle
          location: community/app/target/release
          execution_context_size: "4"

      - name: Package performance runner
        uses: ./.github/actions/nix/nix_run
        env:
          RELEASE_SUFFIX: ${{ steps.release_suffix.outputs.release_suffix }}
        with:
          command: performance/pack-performance.sh

      - name: Remember version info
        uses: ./.github/actions/nix/nix_run
        with:
          command: scripts/ci/generate_info_properties.sh

      - name: Upload performance runner and properties artifact
        uses: actions/upload-artifact@v7
        with:
          name: community-release
          path: |
            canton-performance.tar.gz
            info.properties
          retention-days: 7
