name: Protocol Continuity Test Latest
on:
  workflow_call:
    secrets:
      DATADOG_API_KEY:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      GCLOUD_SERVICE_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: false
      AWS_REGION:
        required: false
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true

permissions:
  actions: write
  contents: read
  issues: write

jobs:
  protocol_continuity_test_latest:
    name: Protocol Continuity Test Latest (shard ${{ matrix.shard }})
    runs-on: dach-ny-canton
    strategy:
      fail-fast: false
      max-parallel: 2
      matrix:
        # Keep in sync with num_test_buckets in run_tests step below
        shard: [0, 1]
    timeout-minutes: 180
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION != '' && secrets.AWS_REGION || 'us-east-1' }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION != '' && secrets.AWS_REGION || 'us-east-1' }}
      AWS_RETRY_MODE: adaptive
      AWS_MAX_ATTEMPTS: "10"
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      EXECUTOR_JVM_HEAP_SIZE: 14000M
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with: {fetch-depth: 0}

      - name: Start Postgres container
        id: postgres
        uses: ./.github/actions/utils/postgres/start_postgres_container_standard
        with:
          shard-index: ${{ matrix.shard }}
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Prepare test inputs and timings
        uses: ./.github/actions/test/prepare_test_inputs_with_timings
        with:
          timings-artifact-name: ${{ github.job }}-timings-latest
          timings-path: ${{ github.job }}/.timings
          github-token: ${{ github.token }}

      - name: Run latest protocol continuity tests
        uses: ./.github/actions/test/run_tests
        with:
          command: dumpClassPath "$RUN_SPLITTED_TESTS_CMD -- -l UnstableTest -l com.digitalasset.canton.annotations.UnstableTest" checkErrors
          execution_context_size: "8"
          include_patterns: '^com\.digitalasset\.canton\.integration\.tests\.continuity\.latest'
          num_parallel_tasks: "1"
          num_test_buckets: "2"
          shard_index: ${{ matrix.shard }}
          timeout: '240m'
          test_file: test-full-class-names.log
          timings_file: ${{ github.job }}/.timings/timings.json

      - name: Stop Postgres container
        if: always()
        uses: ./.github/actions/utils/postgres/stop_postgres_container
        with:
          container-name: ${{ steps.postgres.outputs.container-name }}

  aggregate_shard_outputs:
    name: Aggregate Shard Outputs
    needs: protocol_continuity_test_latest
    if: always()
    uses: ./.github/workflows/_aggregate_test_shard_outputs.yml
    with:
      caller_job: protocol_continuity_test_latest
