name: Scalafix
on:
  workflow_call:
    secrets:
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true

permissions:
  contents: read
  actions: read

jobs:
  scalafix:
    name: Scalafix
    runs-on: dach-ny-canton
    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      EXECUTOR_JVM_HEAP_SIZE: 9000M
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with: {fetch-depth: 0}

      - name: Restore compile and sbt caches
        id: cache_restore
        uses: ./.github/actions/build/restore_compile_sbt_caches

      - name: Run scalafixCheck
        uses: ./.github/actions/sbt/execute_sbt_command
        with:
          cmd: scalafixCheck
          report_to_datadog: "false"
          execution_context_size: "4"
