name: Smoke Test
on:
  workflow_call:
    secrets:
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      DATADOG_API_KEY:
        required: true
      GCLOUD_SERVICE_KEY:
        required: true

permissions:
  contents: read
  actions: write
  issues: write

jobs:
  smoke_test:
    name: Smoke Test
    runs-on: dach-ny-canton
    env:
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      EXECUTOR_JVM_HEAP_SIZE: 14000M
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with: {fetch-depth: 0}

      - name: Start Postgres container
        id: start_postgres
        uses: ./.github/actions/utils/postgres/start_postgres_container_standard
        with:
          shard-index: 0
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Run smoke tests
        uses: ./.github/actions/test/run_tests
        with:
          command: dumpClassPath "community-app/testOnly *.SimplestPingBftOrderingIntegrationTestPostgres"
          execution_context_size: "4"
          num_parallel_tasks: "1"
          num_test_buckets: "0"

      - name: Stop Postgres container
        if: always()
        uses: ./.github/actions/utils/postgres/stop_postgres_container
        with:
          container-name: ${{ steps.start_postgres.outputs.container-name }}

  aggregate_shard_outputs:
    name: Aggregate Shard Outputs
    needs: smoke_test
    if: always()
    uses: ./.github/workflows/_aggregate_test_shard_outputs.yml
    with:
      caller_job: smoke_test
