name: Temp ACS Commitment Tests PV Dev
on:
  workflow_call:
    inputs:
      override_java_version_for_tests:
        default: ""
        type: string
    secrets:
      DATADOG_API_KEY:
        required: true
      DOCKERHUB_USERNAME:
        required: true
      DOCKERHUB_PASSWORD:
        required: true
      GCLOUD_SERVICE_KEY:
        required: true
      AWS_ACCESS_KEY_ID:
        required: true
      AWS_SECRET_ACCESS_KEY:
        required: true
      AWS_SESSION_TOKEN:
        required: false
      AWS_REGION:
        required: false
      MAVEN_USERNAME:
        required: true
      MAVEN_PASSWORD:
        required: true

permissions:
  actions: write
  contents: read
  issues: write

jobs:
  temp_acs_commitment_tests_pv_dev:
    name: temp_acs_commitment_tests_pv_dev
    runs-on: dach-ny-canton
    timeout-minutes: 180
    env:
      DATADOG_API_KEY: ${{ secrets.DATADOG_API_KEY }}
      GCLOUD_SERVICE_KEY: ${{ secrets.GCLOUD_SERVICE_KEY }}
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_SESSION_TOKEN: ${{ secrets.AWS_SESSION_TOKEN }}
      AWS_REGION: ${{ secrets.AWS_REGION != '' && secrets.AWS_REGION || 'us-east-1' }}
      AWS_DEFAULT_REGION: ${{ secrets.AWS_REGION != '' && secrets.AWS_REGION || 'us-east-1' }}
      AWS_RETRY_MODE: adaptive
      AWS_MAX_ATTEMPTS: "10"
      MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
      MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
      DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
      DOCKERHUB_PASSWORD: ${{ secrets.DOCKERHUB_PASSWORD }}
      EXECUTOR_JVM_HEAP_SIZE: 14000M
    steps:
      - name: Checkout
        uses: actions/checkout@v5
        with: {fetch-depth: 0}

      - name: Start Postgres container
        id: postgres
        uses: ./.github/actions/utils/postgres/start_postgres_container_standard
        with:
          shard-index: 0
          dockerhub-username: ${{ secrets.DOCKERHUB_USERNAME }}
          dockerhub-password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Set Canton Protocol Version
        env:
          CANTON_PROTOCOL_VERSION: DEV
        run: |
          echo "CANTON_PROTOCOL_VERSION=$CANTON_PROTOCOL_VERSION" >> "$GITHUB_ENV"
          echo "Canton will use protocol version $CANTON_PROTOCOL_VERSION"
        shell: bash

      - name: Run Temp ACS Commitment Tests
        uses: ./.github/actions/test/run_temp_acs_commitment_tests
        with:
          execution_context_size: '8'

      - name: Stop Postgres container
        if: always()
        uses: ./.github/actions/utils/postgres/stop_postgres_container
        with:
          container-name: ${{ steps.postgres.outputs.container-name }}

  aggregate_shard_outputs:
    name: Aggregate Shard Outputs
    needs: temp_acs_commitment_tests_pv_dev
    if: always()
    uses: ./.github/workflows/_aggregate_test_shard_outputs.yml
    with:
      caller_job: temp_acs_commitment_tests_pv_dev
